jaseci_core/NOTES.md, jaseci_core/jaseci/actions/module/use_actions.py
=> Moved the distance computation out of use_qa's pod into runtime

docs/docs/your-first-jac-program/_category_.json, docs/docs/your-first-jac-program/adding-an-ai-component.md, docs/docs/your-first-jac-program/build-the-jac-code-and-application.mdx, docs/docs/your-first-jac-program/data-models-and-walkers.md, docs/docs/your-first-jac-program/full-demo-code.mdx, docs/docs/your-first-jac-program/next-steps.mdx, docs/docs/your-first-jac-program/overview.md
Add **Your first Jac program** section from current documentation which includes:
- Overview
- Data models and walkers
- Build the Jac code (and application)
- Full demo code
- Next steps
- Adding an AI component
=> add your first jac program section from current documentation

docs/docs/jaseci-extensions/_category_.json, docs/docs/jaseci-extensions/creating-an-extension.md, docs/docs/jaseci-extensions/how-extensions-work.md, docs/docs/utilities/_category_.json, docs/docs/utilities/jaseci-api-wrapper.md
Add **Utilities** section from current documentation. This includes:
- Jaseci API Wrapper
=> Add utilities section from current documentation

docs/docs/jaseci-extensions/_category_.json, docs/docs/jaseci-extensions/creating-an-extension.md, docs/docs/jaseci-extensions/how-extensions-work.md
Add **Jaseci Extensions** section from current documentation. This includes
- How extensions work
- Creating an extension
=> Add Jaseci Extensions from current documentation

docs/jaseci-docs.yaml
kubernetes manifest file for deploying the new docs site built in docusaurus
Closes #51
=> Add k8s manifest for new docs site

docs/docs/resources/_category_.json, docs/docs/resources/common.md
This includes some commonly used Kubernetes commands when working with Jaseci.
=> Add resources section from old documentation

docs/docs/jsctl/_category_.json, docs/docs/jsctl/a-simple-workflow-for-tinkering.md, docs/docs/jsctl/overview.md, docs/docs/jsctl/the-very-basics.md
Added a section to the documentation for **JSCTL**
- Overview
- The very basics
- A simple workflow for tinkering
=> Docs jsctl

ai_serving/README.md, ai_serving/create_ai_service.sh, ai_serving/template/Dockerfile, ai_serving/template/jaseci_ai_service.py, ai_serving/template/jaseci_ai_service.yaml, ai_serving/template/requirements.txt
The `create_ai_service.sh` will automatically create the scaffolding for a new AI service. It saves a lot of manual copy pasting.
Closes #44
=> Template and automate the process of creating a new AI service

jaseci_serv/jaseci_serv/jac_api/tests/ll_wall.jac, jaseci_serv/jaseci_serv/jac_api/tests/test_ll_wall.py, test.sh
update `test.sh`
added walker for testing
- gen_day_workettes
=> Added test for get_gen_day response time

ai_serving/intent_entity/entity_extraction/Dockerfile, ai_serving/intent_entity/entity_extraction/jaseci_ai_serving.yml, ai_serving/intent_entity/entity_extraction/main.py, ai_serving/intent_entity/entity_extraction/requirements.txt, ai_serving/intent_entity/entity_extraction/test.py, ai_serving/intent_entity/intent_extraction/Dockerfile, ai_serving/intent_entity/intent_extraction/jaseci_ai_serving.yml, ai_serving/intent_entity/intent_extraction/main.py, ai_serving/intent_entity/intent_extraction/requirements.txt, ai_serving/intent_entity/intent_extraction/test.py
1. Added docker and serving file
2. Added 7 test cases each in test.py
=> Added the template and test cases

.gitignore, docs/docs/getting-started/jaseci-installation.md, docs/docs/getting-started/start-jaseci-services.md, docs/docs/your-first-jac-program/build-the-jac-code-and-application.mdx, docs/docs/your-first-jac-program/data-models-and-walkers.md, docs/docs/your-first-jac-program/overview.md
Made a small update to the getting started documentation and a fixed some broken links in the tutorial.
=> Documentation Update

jaseci_core/jaseci/jsctl/tests/base1.jac, jaseci_core/jaseci/jsctl/tests/base2.jac, jaseci_core/jaseci/jsctl/tests/base3.jac, jaseci_core/jaseci/jsctl/tests/test_jsctl.py
=> more import tests

ai_serving/encoders/config.cfg, ai_serving/encoders/evaluate.py, ai_serving/encoders/main.py, ai_serving/encoders/models.py, ai_serving/encoders/tokenizer.py, ai_serving/encoders/train.py
Created the module for Bi and Poly encoders
=> encoders initial commit

README.md, jaseci_core/jaseci/api/alias_api.py, jaseci_core/jaseci/api/architype_api.py, jaseci_core/jaseci/api/config_api.py, jaseci_core/jaseci/api/global_api.py, jaseci_core/jaseci/api/graph_api.py, jaseci_core/jaseci/api/logger_api.py, jaseci_core/jaseci/api/master_api.py, jaseci_core/jaseci/api/object_api.py, jaseci_core/jaseci/api/sentinel_api.py, jaseci_core/jaseci/api/super_api.py, jaseci_core/jaseci/api/walker_api.py, jaseci_core/jaseci/jsctl/tests/test_jsctl.py
@ypkang Can you review this. Im thinking you can start reviewing my PRs as a learning tool. We can have calls to talk through them, for fun, learning, and some feedback for me :-).
=> Args qol updates

jaseci_core/jaseci/actions/live_actions.py, jaseci_core/jaseci/actions/remote_actions.py, jaseci_core/jaseci/actions/tests/test_actions.py, jskit/encoders/bi.py, jskit/encoders/biencoder.yaml, jskit/encoders/poly.py, jskit/encoders/sent_enc.py, jskit/encoders/tests/test_biencoder.py, jskit/entity_extraction/entity_extract.yaml, jskit/entity_extraction/entity_extraction.py, jskit/entity_extraction/test_entity.py, jskit/fasttext/fasttext.yaml, jskit/fasttext/fasttext_classifier.py, jskit/intent_extraction/test.py, jskit/text_segmenter/text_segmenter.py, jskit/text_segmenter/text_segmenter.yaml, jskit/use_enc/use_enc.py, jskit/use_qa/use_qa.py, jskit/use_qa/use_qa.yaml
Now uses a single decorators for both local actions and remote actions, everything should work as normal.
=> Actions merge

jskit/encoders/bi.py, jskit/encoders/utils/config.cfg, jskit/encoders/utils/train.py
Please the details of the evaluation
=> Updated mode for  bi-encoder

jaseci_core/jaseci/graph/edge.py, jaseci_core/jaseci/jac/interpreter/architype_interp.py, jaseci_core/jaseci/jac/tests/dot_code.py, jaseci_core/jaseci/jac/tests/test_dot.py
DOT code like the following will successfully save the edge attribute in their context now
```
graph_root -> node_1 [edge=special, name=edge_1]
```
=> Make edge attributes work in DOT

jskit/encoders/bi.py, jskit/encoders/utils/evaluate.py, jskit/encoders/utils/train.py
Change the config loading code for config.cfg to be always using absolute path so that it doesn't fail when loading as local actions.
=> Fix importing issue for library import path for biencoder

examples/JPrime/jprime.jac
A minimal viable version of JPrime is added.
=> Add: JPrime.jac as an example.

support/vscode_extension/jac/syntaxes/jac.tmLanguage.json
Fix syntax highlight for comments...only some were showing.
=> fix syntax highlight for comments

jskit/README.md, jskit/text_segmenter/text_segmenter.py
Fix: A typo
segement -> segment
I think that this should be a typo.
=> Segement typo fix

jaseci_core/jaseci/jsctl/jsctl.py
`jac` -> `js`
`admin` -> `js_admin`
=> Update the API URL in jsctl

jaseci_kit/jaseci_kit/entity_extraction_type_2/config/model_config.json, jaseci_kit/jaseci_kit/entity_extraction_type_2/config/train_config.json, jaseci_kit/jaseci_kit/entity_extraction_type_2/create_data.py, jaseci_kit/jaseci_kit/entity_extraction_type_2/entity_extraction.py, jaseci_kit/jaseci_kit/entity_extraction_type_2/utils.py
Api for entity-extraction-type2 version 1.0
=> entity-extraction-type2 version 1.0

jaseci_kit/jaseci_kit/modules/encoders/bi_enc.yaml, jaseci_kit/jaseci_kit/modules/entity_extraction/flair_ner.yaml, jaseci_kit/jaseci_kit/modules/entity_extraction_type_2/tfm-ner.yaml, jaseci_kit/setup.py
=> Update yaml files for jaseci kit to use jaseci_kit python package for

jaseci_kit/jaseci_kit/modules/pdf_extractor/extractor.py, jaseci_kit/jaseci_kit/modules/pdf_extractor/requierment.txt, jaseci_kit/jaseci_kit/modules/pdf_extractor/tests/test_data.py, jaseci_kit/jaseci_kit/modules/pdf_extractor/tests/test_pdf_ext.py, jaseci_kit/jaseci_kit/pdf_ext.py
Hey @Shawn-Jemmott I have added the PDF extraction method. using PyPDF2  its a light weight pdf text extraction library.
=> Added PDF Text Extraction 

jaseci_kit/jaseci_kit/modules/pdf_extractor/extractor.py, jaseci_kit/jaseci_kit/modules/pdf_extractor/tests/test_pdf_ext.py
=> Add file path option for pdf extractor

jaseci_serv/jaseci_serv/base/models.py
CHANGES:
- Added name and created_date attributes on response
- Added default sorting
- Refactor some process
- **Suggestion rename field from num/start_idx to limit/offset**
=> [MASTER-API]: Update allusers api

jaseci_kit/jaseci_kit/modules/text_segmenter/text_segmenter.yaml
The path is wrong. Please check Ashish's repository.
The alternative way is to clone the main repo instead of ashish's
=> Adjust path to the text segmenter

jaseci_core/jaseci/api/interface.py, jaseci_core/jaseci/api/walker_api.py, jaseci_serv/jaseci_serv/jac_api/api.py, jaseci_serv/jaseci_serv/jac_api/views.py
Removed some unreachable lines
=> [WALKER_API]: Support Query params and raw context payload

jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
Bugfix for Eldon, related to new jaseci standard lib
=> Bugfix, thanks Eldon

jaseci_core/jaseci/actions/standard/jaseci.py
=> Oops forgot this file

README.md
The changes were made to the README.md. I corrected a few grammatical errors and restructured some sentences so that they would flow better.
No.
=> Corrected grammatical errors and restructured some sentences

docs/cronjob, docs/docs/Developing_with_JAC/Language_Features/actions/net.md, docs/docusaurus.config.js, docs/jaseci-docs.yaml, docs/src/theme/prism-include-languages.js, docs/src/theme/prism-jac.js
=> added missing configs and jaseci,yaml file

jaseci_kit/jaseci_kit/modules/use_enc/README.md, jaseci_kit/jaseci_kit/modules/use_qa/README.md
=> use encoder end to end tutorials

jaseci_kit/jaseci_kit/modules/fasttext/README.md
=> fast text end to end tutorials

jaseci_kit/jaseci_kit/modules/summarization/README.md, jaseci_kit/jaseci_kit/modules/t5_sum/README.md, jaseci_kit/jaseci_kit/modules/text_segmenter/README.md
=> end2end tutorial segmenter and summerizer

docs/.gitignore, docs/docs/Developing_with_JAC/API_Development.md, docs/docusaurus.config.js, docs/package.json
=> moved file for better search functionality

docs/jaseci-docs.yaml, jaseci_kit/support/manifests/tfm-ner.yaml
* jaseci-docs deployed in production model
* tfm-ner starting command updated.
=> Two small yaml updates.

support/helmcharts/jaseci/README.md, support/helmcharts/jaseci/templates/aimodelsdeploy.yaml, support/helmcharts/jaseci/templates/deployment.yaml, support/helmcharts/jaseci/values.yaml
Configurable AI models in HELM. plug and play with Ai model installation
new amazing feature
=> Helm ai models added

jaseci_core/jaseci/actor/architype.py, jaseci_core/jaseci/jac/interpreter/interp.py, jaseci_core/jaseci/jac/interpreter/walker_interp.py, jaseci_core/jaseci/tests/jac_test_progs.py, jaseci_core/jaseci/tests/test_progs.py
Finishing a key piece of the inheritance implementation i didnt think of, in particular refencing abstract architypes should work as expected.
=> Seems like this is mostly working, not sure whats breaking

support/helmcharts/jaseci/README.md, support/helmcharts/jaseci/values.yaml
=> Add ingress for production

examples/cai_edu/edges.jac, examples/cai_edu/main.jac, examples/cai_edu/nodes.jac, examples/cai_edu/tests.jac
Work in progress. Need discussion.
Todos:
=> canonicai codelab code for chapter 3

jaseci_core/jaseci/jac/interpreter/interp.py
Added checking if deref syntax argument is already a node
Added backward compatibility for different prefixes (urn. jac, noprefix) 
N/A
No
No
The deref approach since it will not check any prefix on request. It will just append jac prefix once uuid is available
=> [DEREF-SYNTAX]: Node crosscheck and backward compatibility

CHANGELOG.md, jaseci_core/jaseci/jac/interpreter/interp.py, jaseci_core/jaseci/jac/interpreter/tests/fixtures/lang_features.jac, jaseci_core/jaseci/jac/interpreter/tests/test_interp.py, jaseci_core/jaseci/utils/utils.py, support/bible/assets/code/jac_arch_ref_deref.jac
=> Improvements to deref pr.

CHANGELOG.md, jaseci_core/jaseci/actions/standard/jaseci.py, jaseci_core/jaseci/actions/tests/test_std.py, jaseci_core/jaseci/api/interface.py, jaseci_core/jaseci/api/master_api.py, jaseci_core/jaseci/api/sentinel_api.py, jaseci_core/jaseci/api/super_api.py, jaseci_core/jaseci/api/tests/fixtures/hello_world.jac, jaseci_core/jaseci/api/tests/test_global_api.py, jaseci_core/jaseci/api/tests/test_sentinel_api.py, jaseci_core/jaseci/api/tests/test_user_api.py, jaseci_core/jaseci/api/user_api.py, jaseci_core/jaseci/element/master.py, jaseci_core/jaseci/jsctl/jsctl.py, jaseci_core/jaseci/jsctl/tests/test_jsctl.py, jaseci_core/jaseci/tests/test_progs.py, jaseci_serv/jaseci_serv/base/models.py, jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py, jaseci_serv/jaseci_serv/jac_api/views.py
=> New user auto global setup 

jaseci_core/jaseci/api/actions_api.py, jaseci_core/jaseci/api/interface.py, jaseci_core/jaseci/api/master_api.py, jaseci_core/jaseci/api/user_api.py, jaseci_core/jaseci/jsctl/book_tools.py, support/bible/assets/tex/js_generated/api_cheatsheet.tex, support/bible/assets/tex/js_generated/api_spec.tex
=> More doc stuff

jaseci_kit/support/mlflow_integration_HOWTO.md
=> Add MLFlow integration doc markdown

jaseci_kit/support/release_checklist.md
=> Jaseci Kit module release checklist

jaseci_core/jaseci/actor/walker.py, jaseci_core/jaseci/api/tests/test_walker_api.py
=> Update context on subsequent walker_runs with yield

jaseci_core/jaseci/api/alias_api.py, jaseci_core/jaseci/api/user_api.py, jaseci_core/jaseci/api/walker_api.py, jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py, support/bible/assets/tex/js_generated/api_cheatsheet.tex, support/bible/assets/tex/js_generated/api_spec.tex
=> Various additions

examples/cai_edu/chapter_5/edges.jac, examples/cai_edu/chapter_5/main.jac, examples/cai_edu/chapter_5/nodes.jac, jaseci_core/jaseci/actor/walker.py
* Use yield for a non-interactive mode
* Add global root state to direct between FAQ and VA
=> Canonicai -- final coding piece

jaseci_kit/jaseci_kit/modules/encoders/bi_enc.py
update the infer function to return the predicted label additionally
=> infer module update

jaseci_core/jaseci/jac/interpreter/interp.py, jaseci_core/jaseci/tests/jac_test_progs.py, jaseci_core/jaseci/tests/test_progs.py
Bugfix for continue issue pointed out by Chandra
=> test for continue issue found by chandra

jaseci_kit/jaseci_kit/modules/tfm_ner/tests/test_data.py, jaseci_kit/jaseci_kit/modules/tfm_ner/tests/test_entity_extraction.py, jaseci_kit/jaseci_kit/modules/tfm_ner/train.py
=> Updated the prediction to group entities

examples/CanoniCAI/CCAI_codelab.md
Various spelling and grammar changes that make the tutorial easier to read (in my opinion)
No feature changes.
This will not impact Jaseci users.
Nothing in this PR is notable.
=> CanoniCAI Documentation Fix (Mistypes/Grammar, not Content)

jaseci_kit/jaseci_kit/modules/ent_ext/ent_ext.py
=> Flair fixes for train file issue

examples/CanoniCAI/CCAI_codelab.md
Add process ability for dialogue_state intermediate version before introducing cai_state
=> Quick update to CCAI dialogue_state code snippet

examples/CanoniCAI/CCAI_codelab.md
@ypkang Documentation is well done and all functionalities are working like a charm.
=> CCAI Documentation 

jaseci_core/jaseci/svcs/common_svc.py, jaseci_core/jaseci/svcs/mail/mail_svc.py, jaseci_core/jaseci/svcs/redis/redis_svc.py, jaseci_core/jaseci/svcs/task/task_svc.py, jaseci_core/jaseci/utils/app_state.py, jaseci_serv/jaseci_serv/jaseci_serv/settings.py
- common_svc's quiet defaults to True
- task_svc requires redis
N/A
No
No
N/A
=> [ENHANCEMENT]: common_svc's quiet defaults to True; task_svc requires redis_svc

jaseci_serv/jaseci_serv/base/models.py, jaseci_serv/jaseci_serv/user_api/tests/test_user_api.py, jaseci_serv/jaseci_serv/user_api/urls.py, jaseci_serv/jaseci_serv/user_api/views.py
- Added id, is_activated, is_superuser on master_allusers
- Added /user/manage/{id} to update users's is_activated and is_superuser fields
N/A
Yes, test added
N/A
=> [FEATURE-REQUEST]: Additional fields on master_allusers and update user api

jaseci_core/jaseci/actions/standard/tests/test_mail_lib.py, jaseci_core/jaseci/svcs/common_svc.py, jaseci_core/jaseci/svcs/mail/mail_svc.py, jaseci_core/jaseci/svcs/meta_svc.py, jaseci_core/jaseci/svcs/redis/redis_svc.py, jaseci_core/jaseci/svcs/service_state.py, jaseci_core/jaseci/svcs/task/task_svc.py
- Refactor AppState rename to ServiceState
N/A
No
No, unit test update
N/A
=> [UNIT-TEST]: Adjust unit test for email sending

jaseci_core/jaseci/svcs/task/task_svc.py, jaseci_serv/jaseci_serv/svcs/task/task_svc.py
- Use AsyncResult as the main getter for results
- Added initial AsyncResult call for connection testing
N/A
No
No
N/A
=> [ENHANCEMENT]: Change get task by id implementation

examples/CanoniCAI/CCAI_codelab.md
Fixed some instances of spelling / grammatical issues in the codelab that were distracting me. There are likely more typos that I didn't catch.
* Fixed misspelled words
* Fixed sentence grammar issues
* No related issues
* No new features, just improves documentation (?) (technically)
* Marginally better codelab experience
* Not necessarily. Hopefully I'll have something attention-worthy soon :)
=> Fix spelling + unclear wording in CCAI_codelab.md

jaseci_core/jaseci/api/super_api.py, jaseci_serv/jaseci_serv/base/models.py
Unify master_allusers interface between core and serv
=> Unify master_allusers interface between core and serv

jaseci_core/jaseci/actions/live_actions.py, jaseci_core/jaseci/actions/remote_actions.py, jaseci_core/jaseci/element/obj_mixins.py, jaseci_core/jaseci/jac/interpreter/architype_interp.py, jaseci_core/jaseci/utils/id_list.py, jaseci_serv/jaseci_serv/base/tests/test_orm_hooks.py, jaseci_ui_kit/renderer/main.py
=> Some cleaning

jaseci_core/jaseci/actor/sentinel.py, jaseci_core/jaseci/api/walker_api.py
- added `dir` argument to `sentinel.register_walker` and `walker_api.walker_register`
=> Added argument

jaseci_core/jaseci/actions/live_actions.py, jaseci_core/jaseci/actions/remote_actions.py, jaseci_ui_kit/renderer/main.py
=> Finalizing UI Kit v0.1

examples/CanoniCAI/CCAI_codelab.md
Due to several people having problems from forgetting to save their entity extraction model, a reminder will make sure they do.
=> Added reminder to save model in CCAI_codelab.md

jaseci_ui_kit/jac/README.md, jaseci_ui_kit/jac/actions.jac, jaseci_ui_kit/jac/components.jac, jaseci_ui_kit/jac/edges.jac, jaseci_ui_kit/jac/example_site.jac, jaseci_ui_kit/jac/main.jac
Add jac code implementation and example for jaseci_ui_kit
=> UI kit jac implementation 

jaseci_serv/jaseci_serv/jac_api/views.py
=> Hotfix: report_custom scoped in

jaseci_core/jaseci/actions/standard/mail.py, jaseci_core/jaseci/actions/tests/test_std.py, jaseci_core/jaseci/api/jac_api.py, jaseci_core/jaseci/api/tests/test_global_api.py, jaseci_core/jaseci/api/user_api.py, jaseci_core/jaseci/hook/memory.py, jaseci_core/jaseci/jac/tests/test_book.py, jaseci_core/jaseci/jac/tests/test_dot.py, jaseci_core/jaseci/jsctl/jsctl.py, jaseci_core/jaseci/svc/__init__.py, jaseci_core/jaseci/svc/common.py, jaseci_core/jaseci/svc/meta.py, jaseci_core/jaseci/svc/task/common.py, jaseci_core/jaseci/tests/test_core.py, jaseci_core/jaseci/tests/test_jac.py, jaseci_core/jaseci/tests/test_node.py, jaseci_core/jaseci/tests/test_progs.py, jaseci_core/jaseci/utils/json_handler.py, jaseci_core/jaseci/utils/test_core.py, jaseci_serv/jaseci_serv/base/models.py, jaseci_serv/jaseci_serv/base/tests/aitest_ai_models.py, jaseci_serv/jaseci_serv/base/tests/test_models.py, jaseci_serv/jaseci_serv/hook/orm.py, jaseci_serv/jaseci_serv/jac_api/views.py, jaseci_serv/jaseci_serv/svc/meta.py, jaseci_serv/jaseci_serv/user_api/serializers.py
MetaService.build_classes
- this will get and hold all default classes use in other initialization
- hook (RedisHook, OrmHook)
- master (Master, Master (from jsserv))
- super_master (Super, SuperMaster (from jsserv))
- this approach helps the instance to get the right class to be used without declaring
- MetaService.build_* (hook, master, super_master)
MetaService.build_services
- this will add all default services
- task (TaskService)
- redis (RedisService)
- mail (MailService)
- this can be overriden and add default services
MetaService.add_service_builder(
> "nameOfService",
> classOfTheService,
> [args to be used as array],
> {kwargs to be used as dict}
)
- This will add service builder and can be use on later implementation
- some usage example can be StripeSerivce …
=> [META-HANDLER]: Services and Default Classes HANDLER

jaseci_core/jaseci/api/graph_api.py, jaseci_core/jaseci/api/tests/test_graph_api.py, jaseci_core/jaseci/graph/graph.py, jaseci_core/jaseci/tests/test_jac.py
- Added `depth` option for graph get api
N/A
Yes, soon...
No
graph get api
=> [GRAPH-GET]: Add depth option

jaseci_core/jaseci/jac/ir/ast_builder.py, jaseci_core/jaseci/jac/ir/jac_code.py, jaseci_core/jaseci/jac/ir/passes/schedule.py
Refactored ast_builder to remove a bit of circular between itself and the multipass_optimizer.
=> circular reference fix

jaseci_core/jaseci/actor/architype.py, jaseci_core/jaseci/api/jac_api.py, jaseci_core/jaseci/jac/ir/jac_code.py, jaseci_core/jaseci/jac/ir/passes/printer_pass.py, jaseci_core/jaseci/jac/jsci_vm/disasm.py, jaseci_core/jaseci/jsctl/tests/test_jsctl.py
=> Added disassembly feature to jac commands. 

scripts/mdbook_docs.yaml, scripts/tinybox.yaml
=> yaml for mdbooks server in

scripts/mdbook_docs.yaml
=> tweak to mdbooks yaml

README.md, support/guide/other/contributor_policy.md
=> Contributions update

jaseci_core/jaseci/api/user_api.py, jaseci_serv/jaseci_serv/base/models.py, jaseci_serv/jaseci_serv/user_api/tests/test_user_api.py
=> better error erporting for js user create

jaseci_core/jaseci/api/user_api.py, jaseci_serv/jaseci_serv/user_api/tests/test_user_api.py
=> self delete

jaseci_core/jaseci/jac/ir/passes/codegen_pass.py, jaseci_core/jaseci/jac/jsci_vm/inst_ptr.py, jaseci_core/jaseci/jac/jsci_vm/tests/fixtures/unicode.jac, jaseci_core/jaseci/jac/jsci_vm/tests/test_codegen.py, jaseci_core/jaseci/tests/test_core.py
=> bytecode ready

examples/CanoniCAI/CCAI_codelab.md
=> Add jsserv full workflow to canoniCAI codelab

support/codelabs/custom_jaseci_module_codelab.md
Minor update to the codelab, showing how to load a custom module.
=> updated custom jaseci module codelab

jaseci_core/jaseci/api/sentinel_api.py, jaseci_core/jaseci/element/element.py, jaseci_core/jaseci/element/obj_mixins.py, jaseci_core/jaseci/tests/fixtures/simple.jac, jaseci_core/jaseci/tests/fixtures/simple2.jac, jaseci_core/jaseci/tests/test_stack.py
=> Sentinel architype policy

jaseci_core/jaseci/api/sentinel_api.py, jaseci_core/jaseci/tests/test_stack.py
=> Global support in active_snt call

jaseci_serv/jaseci_serv/jac_api/views.py, jaseci_serv/jaseci_serv/user_api/serializers.py
=> Module level request punch through for emails, dirty but fine for now

jaseci_ui_kit/components/src/components/jsc-chip/jsc-chip.tsx, jaseci_ui_kit/components/src/components/jsc-graph/jsc-graph.tsx
=> feat: allow toggling the visibility of node groups

jaseci_ui_kit/components/src/components/jsc-auth-form/jsc-auth-form.tsx
=> [UI Kit] Show error message on invalid login

jaseci_core/jaseci/actor/sentinel.py, jaseci_core/jaseci/actor/walker.py, jaseci_core/jaseci/api/jac_api.py, jaseci_core/jaseci/api/sentinel_api.py, jaseci_core/jaseci/utils/utils.py
=> Better perf stuff

examples/CanoniCAI/codelabs/5_production.md
=> [codelan] Add code snippet for API call

jaseci_ui_kit/components/src/components.d.ts, jaseci_ui_kit/components/src/components/jsc-auth-form/jsc-auth-form.tsx, jaseci_ui_kit/components/src/components/jsc-graph/jsc-graph.tsx
=> feat(UI Kit): allow changing serverUrl for graph viewer and auth form

jaseci_ui_kit/components/src/components/jsc-graph/jsc-graph.tsx
=> switch initial endpoint for graph viewer

jaseci_core/jaseci/__init__.py, jaseci_core/jaseci/actions/live_actions.py, jaseci_core/jaseci/actions/standard/internal.py, jaseci_core/jaseci/actions/standard/tests/fixtures/general.jac, jaseci_core/jaseci/actions/standard/tests/test_std_lib.py
=> New internal libe feature in!

jaseci_serv/jaseci_serv/svc/mail/mail.py
- Adjusting SMTP connection handling
- MYCA's sendgrid issue `please run connect() first`
No
No
Email Sending
=> [EMAIL-SERVICE]: Adjust connection handling for SMTP

CHANGELOG.md, jaseci_core/jaseci/actions/standard/rand.py, jaseci_core/jaseci/actions/standard/std.py, jaseci_core/jaseci/actions/standard/tests/fixtures/general.jac, jaseci_core/jaseci/actions/standard/tests/test_std_lib.py
=> Hot New features: uniform, rounding, with tests and such

examples/CanoniCAI/codelabs/3_dialogue_system.md
=> quick codelab update

jaseci_core/jaseci/actions/standard/date.py, jaseci_core/jaseci/jac/interpreter/architype_interp.py, jaseci_core/jaseci/jac/interpreter/interp.py, jaseci_core/jaseci/jac/machine/jac_scope.py, jaseci_core/jaseci/jac/machine/jac_value.py, jaseci_core/jaseci/tests/fixtures/perf.jac, jaseci_serv/jaseci_serv/jac_api/tests/test_ll.py
=> Attempting ripout

jaseci_core/jaseci/jac/machine/jac_value.py, jaseci_core/jaseci/tests/fixtures/perf.jac
=> perf demo added

jaseci_ai_kit/jaseci_ai_kit/modules/ent_ext/config.cfg
changed the default config to tars ner
=> updating default config for ent_ext(flair)

jaseci_core/jaseci/jac/interpreter/interp.py, jaseci_core/jaseci/jac/machine/machine_state.py, jaseci_serv/jaseci_serv/jac_api/tests/ll_wall.jac, jaseci_serv/jaseci_serv/jac_api/tests/test_ll_wall.py
=> Bugfix for Alexie

jaseci_core/jaseci/actions/standard/tests/test_net_lib.py, jaseci_core/jaseci/graph/edge.py, jaseci_core/jaseci/graph/node.py, jaseci_core/jaseci/jac/machine/machine_state.py, jaseci_core/jaseci/jsctl/jsctl.py, jaseci_core/jaseci/tests/fixtures/ll_perf.jac, jaseci_core/jaseci/tests/fixtures/ll_perf_script, jaseci_core/jaseci/tests/test_core.py, jaseci_core/jaseci/tests/test_node.py, jaseci_core/jaseci/utils/id_list.py, jaseci_serv/jaseci_serv/base/tests/test_orm_hooks.py
=> Fast Edges

jaseci_core/jaseci/graph/edge.py, jaseci_core/jaseci/graph/node.py, jaseci_core/jaseci/utils/id_list.py, jaseci_serv/jaseci_serv/base/tests/test_orm_hooks.py, jaseci_serv/jaseci_serv/jac_api/tests/test_ll.py
=> Fast edge prod fix

README.md, jaseci_ai_kit/jaseci_ai_kit/README.md
Including the guidelines for creating the testcases for Jaseci-AI- Kit
=> Guidelines of creating Tests for Jaseci-Ai-Kit

docs/docs/canonicai/chapter9.md
=> stand up a jaseci_ai_kit server locally

jaseci_core/jaseci/graph/edge.py, jaseci_core/jaseci/graph/node.py, jaseci_serv/jaseci_serv/base/tests/test_orm_hooks.py
=> full fast edges

jaseci_ai_kit/jaseci_ai_kit/modules/fast_enc/config.py, jaseci_ai_kit/jaseci_ai_kit/modules/fast_enc/fast_enc.py, jaseci_ai_kit/jaseci_ai_kit/modules/fast_enc/tests/fixtures/fast_enc.jac, jaseci_ai_kit/jaseci_ai_kit/modules/fast_enc/tests/test_fast_enc.py
testing update and resolved the Dir structure issue
=> Fast Enc Testing Update - new format

jaseci_ai_kit/jaseci_ai_kit/modules/pdf_ext/tests/fixtures/pdf_ext.jac, jaseci_ai_kit/jaseci_ai_kit/modules/pdf_ext/tests/test_pdf_ext.py, jaseci_ai_kit/jaseci_ai_kit/modules/text_seg/tests/fixtures/text_seg.jac, jaseci_ai_kit/jaseci_ai_kit/modules/text_seg/tests/test_text_seg.py
=> More AI Kit Tests

jaseci_ai_kit/jaseci_ai_kit/modules/ent_ext/tests/fixtures/ent_ext.jac, jaseci_ai_kit/jaseci_ai_kit/modules/ent_ext/tests/test_ent_ext.py
=> EntExt (flair) tests- new format

jaseci_ai_kit/jaseci_ai_kit/modules/t5_sum/tests/fixtures/t5_sum.jac, jaseci_ai_kit/jaseci_ai_kit/modules/t5_sum/tests/test_t5_sum.py
created T5Sum Tests as per the new format
=> T5Sum Tests - new format

README.md
Had to change the relative path for the ui_docs so mdbook can be rendered.
=> updated readme to bring in ui_kit docs

jaseci_ai_kit/jaseci_ai_kit/modules/cluster/README.md
=> added readme

docs/docs/canonicai/chapter7.md
@marsninja @ypkang Tested it and it works fine. Will show in the upcoming meeting.
=> adding test to canonicai

jaseci_core/jaseci/api/logger_api.py, jaseci_core/jaseci/api/tests/fixtures/test_logging.jac, jaseci_core/jaseci/api/tests/test_logger_api.py, jaseci_core/jaseci/utils/log_utils.py, jaseci_core/jaseci/utils/utils.py
Add a new endpoint `logger_get_logs` for retrieving logs
=> Add endpoint for viewing logs

support/backup/velero/README.md
=> readme-Velero-support init

jaseci_core/jaseci/jac/interpreter/interp.py, jaseci_core/jaseci/jac/machine/machine_state.py, jaseci_core/jaseci/tests/fixtures/simple.jac, jaseci_core/jaseci/tests/test_stack.py
=> Tmp deep except

jaseci_studio/README.md, jaseci_studio/__e2e__/logs.spec.ts, jaseci_studio/src/components/LogsViewer/LevelFilter.tsx, jaseci_studio/src/components/LogsViewer/LogsViewer.tsx, jaseci_studio/src/pages/logs.tsx
=> Add scroll actions, pausing logs, and level filter to logs viewer

.github/workflows/jaseci-serv-test.yml, jaseci_serv/jaseci_serv/settings.py, jaseci_serv/jaseci_serv/svc/task/config.py
=> Quick fix for elegance

ui_components/src/components/graph-walker-runner/graph-walker-runner.tsx, ui_components/src/components/jsc-app/readme.md, ui_components/src/components/jsc-graph/jsc-graph.tsx, ui_components/src/components/jsc-graph/readme.md
=> Update graph-viewer ui

jaseci_core/jaseci/__init__.py, jaseci_core/jaseci/actions/live_actions.py, jaseci_core/jaseci/actions/standard/tests/fixtures/webtool.jac, jaseci_core/jaseci/actions/standard/tests/test_webtool.py, jaseci_core/jaseci/actions/standard/webtool.py, jaseci_core/setup.py
- added action that parse metadata out of urls
=> Add webtool action

jaseci_core/jaseci/api/tests/test_logger_api.py, jaseci_core/jaseci/utils/log_utils.py, jaseci_core/jaseci/utils/utils.py
=> replace StringIO buffer with limited sliding buffer for logging

jaseci_ai_kit/jaseci_ai_kit/modules/translator/.gitignore, jaseci_ai_kit/jaseci_ai_kit/modules/translator/README.md, jaseci_ai_kit/jaseci_ai_kit/modules/translator/tests/fixtures/translator.jac, jaseci_ai_kit/jaseci_ai_kit/modules/translator/tests/test_translator.py, jaseci_ai_kit/jaseci_ai_kit/modules/translator/translator.py, jaseci_ai_kit/jaseci_ai_kit/new_module.sh, jaseci_ai_kit/jaseci_ai_kit/translator.py
* Module that supports multilingual translation
=> Multilingual Translation

.github/workflows/build-and-release-studio.yml
=> add workflow file for building jaseci studio

jaseci_studio/src-tauri/tauri.conf.json, jaseci_studio/src/pages/graph-viewer/index.tsx, ui_components/src/components/graph-node-info/graph-node-info.css, ui_components/src/components/graph-node-info/graph-node-info.spec.tsx, ui_components/src/components/graph-node-info/graph-node-info.tsx, ui_components/src/components/graph-node-info/readme.md, ui_components/src/components/graph-walker-runner/graph-walker-runner.tsx, ui_components/src/components/jsc-graph/jsc-graph.spec.tsx, ui_components/src/components/jsc-graph/jsc-graph.tsx, ui_components/src/components/jsc-graph/utils.ts
=> Graph viewer UI refactor

.github/workflows/build-and-release-studio.yml
=> Update studio release workflow

CHANGELOG.md, jaseci_core/jaseci/jsctl/jsctl.py, jaseci_core/jaseci/jsctl/tests/test_jsctl.py, jaseci_core/setup.py, support/guide/other/DOCTODOS.md
=> Standalone Jac cli

examples/CanoniCAI/CCAI_codelab.md, examples/CanoniCAI/codelabs/6_speech2text_and_text2speech.md, examples/CanoniCAI/codelabs/7_crowdsource.md, examples/CanoniCAI/codelabs/8.contributing_to_jaseci.md
=> stt and tts codelab

.github/workflows/build-and-release-studio.yml
=> change jaseci studio version to be semantic version compatible

ui_components/src/components/graph-node-info/graph-node-info.tsx, ui_components/src/components/graph-node-info/readme.md, ui_components/src/components/jsc-app/readme.md, ui_components/src/components/jsc-graph/readme.md
=> resolve build errors for ui_components

jaseci_studio/__tests__/ServerInfo.test.tsx, jaseci_studio/src/components/ServerInfo.tsx, jaseci_studio/src/pages/dashboard/index.tsx
=> Display server info beside summary view

.github/workflows/build-and-release.yml
=> [ypk] Add delay before docker hub push

jaseci_core/jaseci/api/prometheus_api.py, jaseci_core/jaseci/element/super_master.py, jaseci_core/jaseci/svc/prometheus/manifest.py
* Added a set of promethues APIs
* Fix promethues node exporter manifest (node metrics used to not work for cluster in WSL environment)
=> Prometheus node exporter fix and new Jaseci APIs for prometheus

jaseci_core/jaseci/actions/live_actions.py
=> Unload action module improvement -- explicit delete objects to free memory

ui_components/src/components/jsc-graph/jsc-graph.spec.tsx, ui_components/src/components/jsc-graph/jsc-graph.tsx
=> feat: expand nodes recursively; expand and collapse multiple nodes simultaneously

jaseci_studio/.gitignore, jaseci_studio/export_studio.sh, jaseci_studio/format_templates.py
=> [WIP] Make jaseci_studio work with jaseci_serv

.github/workflows/jaseci-studio-test.yml, jaseci_studio/__e2e__/logs.spec.ts, jaseci_studio/mocks/logs.handlers.ts, jaseci_studio/package.json
=> add github workflow for running tests for jaseci studio

.github/workflows/build-and-release.yml
=> Docker images are tagged with latest now

README.md, support/docker/how_to_package.md
=> Add guide on how to create a release/deployment ready jaseci package

jaseci_ai_kit/support/manifests/ph.yaml
=> Add a PH manifest yaml with PVC

jaseci_core/jaseci/svc/postgres/manifest.py
=> Add postgres manifest dict for jsorc integration

jaseci_ai_kit/jac_misc/jac_misc/ph/utils/dataloader.py
Specify your collate_fn in the custom.py. When making dataloaders it will be used.
Closes #857
=> Ability parse a Custom Collate Function (PH)

jaseci_ai_kit/.gitignore, jaseci_ai_kit/jac_speech/setup.py
=> Platform Specific Requirements

ui_components/src/components/jsc-graph/jsc-graph.spec.tsx, ui_components/src/components/jsc-graph/jsc-graph.tsx
=> fix for hiding nodes and allow hiding edges

support/vscode_extension/jac/syntaxes/jac.tmLanguage.json
=> Update VSCode extension with new keywords

jaseci_ai_kit/jac_nlp/jac_nlp/use_enc/README.md
=> batch encoding documentation

docs/docs/getting-started/installation.md, support/guide/getting_started/quickstart.md
+ Added support for how to change default version of python
+ Updated output of help
=> update python install guide, update help output

CONTRIBUTING.md, README.md, docs/docs/Introduction/Architecture_of_jaseci.md, docs/docs/Introduction/What_and_why_jaseci.md, docs/docs/Introduction/abstraction_of_jaseci.md, docs/docs/getting-started/jac_ai_kit_and_graphiz.md, docs/docs/getting-started/jaseci_studios.md, docs/docs/interfacing_jaseci/api_collection.md, docs/docs/interfacing_jaseci/basics.md, docs/docs/interfacing_jaseci/jsctl.md, docs/package.json, support/guide/getting_started/quickstart.md
The introduction and Getting Started aspects of the Documentation were rearranged, and some new sections were introduced according to the outline of the proposed structure of the documentation.
=> Jaseci Documentation Changes

examples/CanoniCAI/codelabs/5_production.md
When the user is working on the tutorial, there is no "main.jac", it should be "tesla_ai.jac" and "tesla_ai.jir"
=> Update commands in section 7.5

support/guide/getting_started/installation.md
=> Update installation guide

jaseci_core/jaseci/svc/common.py, jaseci_core/jaseci/svc/config.py, jaseci_core/jaseci/svc/meta.py, jaseci_core/setup.py, scripts/jsorc/jaseci.yaml
=> [JSORC]: DB Regen

README.md, docs/docs/Developing_with_JAC/Language_Features/actions/file.md, docs/docs/Developing_with_JAC/Language_Features/function.md, docs/docs/Developing_with_JAC/Language_Features/globals.md, docs/docs/Developing_with_JAC/Language_Features/imports.md
Good Night Dr Mars and team, I migrated content from the jaseci bible to the File Handling, globals, and functions section. Additionally, I added an import section in the language basics category with the relevant content. The import are present in a codelab in the docs but I believe that its not explained in detail and you can't easily find it to I added a section dedicated to it along with the relevant content.
=> Jaseci Documentation Upgrade

ui_components/src/components.d.ts, ui_components/src/components/jsc-app/readme.md, ui_components/src/components/jsc-graph/graph-context-menu.spec.tsx, ui_components/src/components/jsc-graph/graph-context-menu.tsx, ui_components/src/components/jsc-graph/jsc-graph.spec.tsx, ui_components/src/components/jsc-graph/jsc-graph.tsx, ui_components/src/components/jsc-graph/mockData/initial_graph_node_view.json, ui_components/src/components/jsc-graph/readme.md, ui_components/src/components/jsc-graph/utils.ts, ui_components/src/components/jsc-select/readme.md
=> add ability to set how node groups are displayed

jaseci_studio/__tests__/ArchitypeList.test.tsx, jaseci_studio/__tests__/RunWalker.test.tsx, jaseci_studio/mocks/handlers.ts, jaseci_studio/mocks/walker.handlers.ts, jaseci_studio/package.json, jaseci_studio/src/components/ArchitypeList.tsx, jaseci_studio/src/components/Editor.tsx, jaseci_studio/src/components/RunWalker.tsx, jaseci_studio/src/hooks/useRunWalker.tsx, jaseci_studio/src/pages/architype.tsx, jaseci_studio/yarn.lock
=> Add tab for running walkers on architype view

jaseci_serv/jaseci_serv/studio/tests/mocks_templates/studio/index.html, jaseci_serv/jaseci_serv/studio/tests/test_studio_routes.py, jaseci_serv/jaseci_serv/studio/urls.py, jaseci_serv/jaseci_serv/studio/views.py, jaseci_serv/jaseci_serv/urls.py, jaseci_studio/export_studio.sh, jaseci_studio/format_templates.py, jaseci_studio/next.config.js, jaseci_studio/package.json, jaseci_studio/src-tauri/tauri.conf.json, jaseci_studio/src/components/ArchitypeList.tsx, jaseci_studio/src/components/ChangeGraphModal.tsx, jaseci_studio/src/components/LoginForm.tsx, jaseci_studio/src/components/LogsViewer/LogsViewer.tsx, jaseci_studio/src/components/Navbar.tsx, jaseci_studio/src/components/RunWalker.tsx, jaseci_studio/src/hooks/useGetMasterAllUsers.tsx, jaseci_studio/src/pages/_app.tsx, jaseci_studio/src/pages/architype.tsx, jaseci_studio/theme.ts, jaseci_studio/yarn.lock
=> Add studio route to jsserv

jaseci_core/jaseci/jsctl/jsctl.py, jaseci_studio/src/components/LoginForm.tsx, jaseci_studio/src/components/ReactQuery.tsx
=> add jsctl studio command to launch studio with authenticated session

jaseci_serv/setup.py, jaseci_studio/export_studio.sh
=> add install command to jaseci_serv setup file

README.md, support/guide/other/contributor_policy.md
`Readme.md`
- corrected minor grammatical errors
`contributor_policy.md`
- small spelling fix
-  changed line ending to LF to be consistent with other files in repo.
=> minor readme grammer fixes

jaseci_studio/src/hooks/useUserInfo.tsx
=> Fix (studio): Update user-info url to prevent redirect

jaseci_core/jaseci/extens/act_lib/tests/fixtures/webtool.jac, jaseci_core/jaseci/extens/act_lib/tests/test_webtool.py, jaseci_core/jaseci/extens/act_lib/webtool.py, jaseci_core/setup.py
Also add `html5lib` parser option for future proof.
=> Update webtool get_meta with timeout and headers

jaseci_serv/jaseci_serv/jsx_oauth/HOWTO.md, jaseci_serv/jaseci_serv/jsx_oauth/admin.py, jaseci_serv/jaseci_serv/jsx_oauth/config.py, jaseci_serv/jaseci_serv/jsx_oauth/models.py, jaseci_serv/jaseci_serv/jsx_oauth/tests/test_social_auth.py, jaseci_serv/jaseci_serv/jsx_oauth/urls.py, jaseci_serv/jaseci_serv/jsx_oauth/utils.py, jaseci_serv/jaseci_serv/jsx_oauth/views.py, jaseci_serv/jaseci_serv/settings.py, jaseci_serv/templates/examples/social_auth.html
=> [SOCIAL-AUTH]: Apple sign-in and refactor

jaseci_core/jaseci/extens/api/jsorc_api.py, jaseci_core/jaseci/jsorc/jsorc.py
New API:
- jsorc_refresh: update jsorc's config
- service_info: return's current service informations
=> [JSORC]: Bugfix and enhancements

jaseci_core/jaseci/jsorc/manifests/prometheus.yaml
Add manifest for grafana visualization dashboard.
=> Grafana/Prometheus 

jaseci_core/jaseci/extens/svc/kube_svc.py, jaseci_core/jaseci/jsorc/jsorc_utils.py, jaseci_core/jaseci/jsorc/manifests/prometheus.yaml, jaseci_core/jaseci/jsorc/tests/fixture/elastic_resources.py, jaseci_core/jaseci/jsorc/tests/test_jsorc.py, scripts/jsorc/kube_apply_jaseci.sh
CHANGES:
- Remove prometheus and elastic on default jsorc script
- enhance jsorc parser
- jsorc dedicated namespace
=> [JSORC]: Enhancements

docs/docs/docs/development/std_actions/9_stripe.md, jaseci_core/jaseci/extens/act_lib/stripe.py, jaseci_core/jaseci/extens/api/user_api.py, jaseci_core/jaseci/extens/api/webhook_api.py, jaseci_core/jaseci/tests/fixtures/stripe.jac, jaseci_core/jaseci/tests/test_stripe.py, jaseci_serv/jaseci_serv/base/models.py, jaseci_serv/jaseci_serv/user_api/serializers.py
This is to allow developer to use stripe [api docs](https://stripe.com/docs/api) as reference
=> [STRIPE]: Align actions to stripe api specs

jaseci_core/jaseci/extens/api/webhook_api.py
CHANGES:
- Prioritize request metadata and use customer metadata as fallback
=> [STRIPE-WEBHOOK]: Allow cross checking of reference between customer and request metadata

jaseci_core/jaseci/extens/svc/tasks.py, jaseci_serv/jaseci_serv/svc/tests/test_task_svc.py, jaseci_serv/jaseci_serv/svc/tests/testing.jac
=> [MINOR]: Scheduled Walker/Sequence commiter

docs/docs/docs/development/std_actions/9_stripe.md, jaseci_core/jaseci/extens/act_lib/stripe.py, jaseci_core/jaseci/extens/api/webhook_api.py, jaseci_core/jaseci/tests/fixtures/stripe.jac, jaseci_core/jaseci/tests/test_stripe.py
CHANGES:
- Added subscription_item_list_usage_record_summaries
- Added unit test
=> [BUGFIX]: Stripe adjustment for certificate validation due to FileHandler changes

jaseci_core/jaseci/jsorc/live_actions.py, jaseci_core/jaseci/jsorc/remote_actions.py, jaseci_core/jaseci/jsorc/tests/test_actions.py
=> [HOTFIX-V1]: Remote action support *args and *kwargs

jaseci_core/jaseci/prim/edge.py, jaseci_core/jaseci/prim/node.py, jaseci_core/jaseci/tests/jac_test_code.py, jaseci_core/jaseci/utils/id_list.py, jaseci_serv/jaseci_serv/base/tests/test_orm_hooks.py, jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
Not fully tested yet but it's a possible fix on current issue on all nodes are being save when traversing
=> [HOTFIX]: Bypass node saving when smart building edges

docs/package.json
Reverts Jaseci-Labs/jaseci#1243
=> Revert "Update docusaurus version"

.github/workflows/pre_commit.yml, jaclang/.pre-commit-config.yaml, jaclang/CHANGELOG
=> config: test

jac-mtllm/pyproject.toml
Works for any version above jaclang 0.7.16
=> mtllm dependency loosening.

README.md
Add simple README for the mono-repo
=> Add simple main README

jac/support/jac-lang.org/docs/learn/tutorial/2_building-a-rag-chatbot.md
Quick bug fix in the tutorial when importing `rag.py`
=> Bug fix in tutorial

jac/jaclang/compiler/passes/main/__init__.py, jac/jaclang/plugin/tests/test_jaseci.py, jac/jaclang/runtimelib/memory.py
- fix architype not updating
- fix unit test wrong assertion
=> [HOTFIX]: Architype not updating

jac/jaclang/runtimelib/architype.py, jac/jaclang/tests/fixtures/entry_exit.jac, jac/jaclang/tests/test_language.py
This PR provides a fix for Issue #1313
=> Fix : Undesired Behavior on Walker With Entry and With Exit

jac-cloud/jac_cloud/core/context.py, jac-cloud/jac_cloud/plugin/jaseci.py, jac-cloud/jac_cloud/tests/openapi_specs.json, jac-cloud/jac_cloud/tests/simple_graph.jac
=> [MINOR]: Dynamic return types

jac-cloud/jac_cloud/core/architype.py, jac-cloud/jac_cloud/core/context.py, jac-cloud/jac_cloud/core/memory.py, jac-cloud/jac_cloud/plugin/jaseci.py, jac-cloud/jac_cloud/tests/simple_graph.jac, jac/.pre-commit-config.yaml, jac/examples/micro/simple_walk_by_edge.jac, jac/jaclang/__init__.py, jac/jaclang/cli/cli.py, jac/jaclang/plugin/builtin.py, jac/jaclang/plugin/default.py, jac/jaclang/plugin/feature.py, jac/jaclang/plugin/spec.py, jac/jaclang/plugin/tests/fixtures/other_root_access.jac, jac/jaclang/plugin/tests/test_features.py, jac/jaclang/runtimelib/architype.py, jac/jaclang/runtimelib/constructs.py, jac/jaclang/runtimelib/context.py, jac/jaclang/runtimelib/memory.py, jac/jaclang/tests/fixtures/edge_node_walk.jac, jac/jaclang/tests/fixtures/edges_walk.jac, jac/jaclang/tests/fixtures/gendot_bubble_sort.jac, jac/jaclang/tests/test_language.py
- Migrate all logical process to pluggy in preparation for Abstractions approach
=> [REFACTOR]: Migrate all process to pluggy

jac-cloud/setup.py
This release contains bug fixes and features:
- #1346
- #1339 
- #1316
=> Release jac-cloud v0.1.3

jac/jaclang/plugin/plugin.md, jac/jaclang/plugin/spec.py
```python
def allow_root(
architype: Architype,
root_id: UUID,
level: AccessLevel | int | str
) -> None:
"""Allow all access from target root graph to current Architype."""
```
```python
def disallow_root(
architype: Architype,
root_id: UUID,
level: AccessLevel | int | str
) -> None:
"""Disallow all access from target root graph to current Architype."""
```
```python
def unrestrict(
architype: Architype,
level: AccessLevel | int | str
) -> None:
"""Allow everyone to access current Architype."""
```
```python
def restrict(
architype: Architype
) -> None:
"""Disallow others to access current Architype."""
```
```python
def check_read_access(
to: Anchor
) -> bool:
"""Read Access Validation."""
```
```python
def check_connect_access(
to: Anchor
) -> bool:
"""Connect Access Validation."""
``` …
=> [PLUGIN]: Specs Docs

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/passes/main/tests/fixtures/fstrings.jac, jac/jaclang/tests/test_language.py
=> Fix: Docstring bug

jac-splice-orc/managers/pod_manager.py
=> variableize image name

jac-cloud/jac_cloud/core/architype.py
CHANGES:
- Manually assign fields from datasource based on dataclass fields
- Value error will be raised
- if field is required but not existing from db
- if field has different type from db
- default will get populated if field has default/factory and not existing from db
- excess fields will be included but no type checking
OLD:
- Uses __init__ generated by dataclass
=> [JAC-CLOUD]: Improved Deserialization

jac/jaclang/langserve/engine.py, jac/jaclang/langserve/server.py
=> Trigger Deep Check on Save for Modified Files Only

jac/support/jac-lang.org/docs/learn/tutorial/1_setting-up-jac-cloud.md
=> Tutorial update for not requiring mongodb

jac/jaclang/compiler/parser.py, jac/jaclang/tests/fixtures/glob_multivar_statement.jac, jac/jaclang/tests/test_language.py
=> [fix] :g: keyword does not support multiple variables in a statement

jac-mtllm/examples/inherit_basellm.jac, jac-mtllm/mtllm/aott.py, jac-mtllm/mtllm/plugin.py, jac-mtllm/mtllm/utils.py
=> Refine Prompt Structure: Add Section Headers Conditionally

jac/support/jac-lang.org/docs/learn/coders/jac-cloud/docs/permission.md
This PR adds documentation for key permission management APIs, detailing the main endpoints and their usage.
=> [Documentation Update] Overview of Common Permission Management APIs

jac-splice-orc/ReadMe.md
updated usage section in readme
=> updated readme splice-orc

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/jac.lark, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/def_use_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/sym_tab_build_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/tests/fixtures/multi_dim_array_split.jac, jac/jaclang/tests/test_language.py, jac/support/jac-lang.org/docs/learn/jac_ref.md
=> multi dim array split syntax support

jac/jaclang/runtimelib/memory.py
```python
n = NodeAnchor.Collection.find_one(filter=filter);
if exist := Jac.get_context().mem.is_cached(n){
logger.info("jaseci_sdk | get_node | node already exists in memory");
n = exist;
}
else {
logger.info("jaseci_sdk | get_node | node not found in memory");
logger.info("jaseci_sdk | get_node | syncing node to memory...");
Jac.get_context().mem.set(n.id, n);
}
```
=> [MINOR]: Memory checker if data already cached

jac/jaclang/plugin/default.py, jac/jaclang/plugin/feature.py, jac/jaclang/plugin/spec.py, jac/jaclang/plugin/tests/fixtures/other_root_access.jac, jac/jaclang/plugin/tests/test_jaseci.py
Support elevate current root to be system root
=> [FEATURE]: Elevate Root

README.md
=> Showcase Projects added

jac-mtllm/mtllm/aott.py
=> {BUG) Fix for input information issue in MTLLM

jac-cloud/jac_cloud/core/architype.py, jac-cloud/jac_cloud/tests/simple_graph.jac, jac-cloud/jac_cloud/tests/test_simple_graph.py, jac/jaclang/runtimelib/utils.py
```js
import:py from typing {Any}
node A {
has val: int;
}
node B {
has val: str | int;
}
node C {
has val: Any;
}
```
=> [FEATURE]: Support UnionTypes and Any

jac-splice-orc/docker/Dockerfile, jac-splice-orc/jac_splice_orc/config/config.json, jac-splice-orc/jac_splice_orc/config/config_loader.py, jac-splice-orc/jac_splice_orc/managers/pod_manager.py, jac-splice-orc/jac_splice_orc/plugin/splice_plugin.py, jac-splice-orc/jac_splice_orc/server/server.py, jac-splice-orc/jac_splice_orc/utils/startup.sh, jac-splice-orc/requirements.txt, jac-splice-orc/setup.py
**Key Changes:**
1. **Dockerfile:**
- Updated dependencies installation and adjusted file copy strategy.
- Included entire application directory for simplicity.
2. **Config Updates:**
- Adjusted image version in `config.json`.
- Added new dependencies like `sentence-transformers`.
3. **Code Refactor:**
- Enhanced ConfigLoader for dynamic file path handling.
- Modularized pod creation logic with error handling and better namespace configuration.
4. **Cluster-Specific Adjustments:**
- Service type and port logic tailored for `kind` clusters.
- Improved detection and handling for non-standard clusters.
5. **Startup Scripts:**
- Enhanced modularity and logging in `startup.sh`.
- Improved handling for module requirements.
6. **Package Updates:**
- Updated requirements to include missing …
=> Enhancements and Refactor: JAC Splice-Orchestrator

jac-cloud/jac_cloud/jaseci/routers/user.py, jac-cloud/jac_cloud/tests/openapi_specs.yaml
=> [MINOR]: Login logs

jac-mtllm/mtllm/aott.py
=> Enable passing custom parameters for custom model

jac/jaclang/cli/cli.py, jac/jaclang/plugin/default.py, jac/jaclang/plugin/feature.py, jac/jaclang/plugin/spec.py, jac/jaclang/runtimelib/test.py, jac/jaclang/tests/fixtures/jactest_imported.jac, jac/jaclang/tests/fixtures/jactest_main.jac, jac/jaclang/tests/test_cli.py
```
jac test -t some_test_func_name file.jac
```
=> jac test runs for specific file and func

jac/jaclang/utils/helpers.py
Runtime error report fails on python 3.12 (because we were using an internal python attribute, which we shouldn't use), this is fixed and will work on all python version (has a fallback value if the attribute is not available too).
=> runtime error report fails on python 3.12 fix

jac/support/jac-lang.org/docs/learn/littleX/src/Jac_cloud_example.jac, jac/support/jac-lang.org/docs/learn/littleX/src/kind-config.yaml, jac/support/jac-lang.org/docs/learn/littleX/src/mtllm_example.jac, jac/support/jac-lang.org/docs/learn/littleX/tutorial.md
1. Jaseci Overview, LittleX Overview - Done
2. Run LittleX on Local Enviornment - Done
3. Guide for beginners
- Introduction to Graph - Done
- Introduction to Data spatial Programming - Done
- Understanding Jaclang - Done
- Integrate AI using MTLLM - Done
- Deploy using Jac-cloud - Done
- Microservice using Jac-splice-orc - Done
=> Jaseci cookbook

jac-cloud/jac_cloud/plugin/jaseci.py, jac/jaclang/plugin/default.py, jac/jaclang/runtimelib/architype.py, jac/support/jac-lang.org/docs/learn/coders/jac-cloud/docs/permission.md
1. roots access config of target node
2. roots access config of target node's root
3. public (all) access config of target node's root
4. public (all) access config of target node
=> [APPROACH #2][ACCESS-CHANGE]: Prioritize sequence access level permission

jac/examples/reference/elvis_expressions.jac, jac/examples/reference/elvis_expressions.py, jac/jaclang/compiler/__init__.py, jac/jaclang/compiler/constant.py, jac/jaclang/compiler/jac.lark, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/plugin/default.py, jac/jaclang/plugin/feature.py, jac/jaclang/plugin/spec.py, jac/support/jac-lang.org/docs/learn/jac_ref.md
=> elvis operator was removed.

jac/jaclang/compiler/parser.py
Modified So far
import_path
import_items
import_item
architype
architype_decl
enum
enum_decl
enum_stmt
=> Modify Parser Functions for Imports, Architypes, and Enums

jac/jaclang/compiler/parser.py
Modified Parser Functions
- ability
- ability_decl
- abstract_ability
- genai_ability
- event_clause
- if_stmt
- elif_stmt
- else_stmt
- try_stmt
- except_list
- except_def
- finally_stmt
=> [Parser-Refactor] Modify Parser Functions for ability, if and try

jac/jaclang/compiler/parser.py
i edited check_stmt,ctrl_stmt , delete_stmt , report_stmt , return_stmt , ignore_stmt , disengage_stmt ,revisited_stmt , visit_stmt and global and nonlocal statements
=> [Parser-Refactor] Modify Statement functions

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/pyout_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/compiler/passes/tool/tests/fixtures/genai/joke_gen.jac, jac/jaclang/compiler/passes/tool/tests/fixtures/genai/odd_word_out.jac, jac/jaclang/compiler/passes/tool/tests/fixtures/genai/wikipedia.jac, jac/jaclang/compiler/symtable.py
=> [SubnodeList-Remove] Removed from ListVal

jac/jaclang/compiler/parser.py
=> renaming self.node to self.cur_node in parser breaks main fixed.

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py
=> [Subnode-Remove-2] Removed from SetVal

jac/jaclang/compiler/parser.py
Modified Functions
- as_pattern
- pattern
- literal_pattern
- singleton_pattern
- sequence_pattern
- mapping_pattern
- list_inner_pattern
- bitwise_or
- bitwise_xor
- bitwise_and
- shift
- dict_inner_pattern
- capture_pattern
- or_pattern
- pattern_seq
=> [Parser-Refactoring] - 4th PR

jac/jaclang/compiler/parser.py
i edited arch_ref , node_ref , edge_ref ,walker_ref , class_ref , object_ref , type_ref , enum_ref functions
=> Refactor Jaclang reference functions in parser

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/def_impl_match_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/pyjac_ast_link_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/compiler/passes/tool/tests/fixtures/corelib_fmt.jac, jac/jaclang/compiler/passes/tool/tests/fixtures/doc_string.jac, jac/jaclang/compiler/passes/tool/tests/fixtures/myca_formatted_code/simple_walker.jac, jac/jaclang/tests/test_language.py
=> [Subnodelist-Remove] Removed from FuncSignature

.gitignore
=> Exclude MyPy cache files

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/tests/test_language.py
=> subnode list removed from for in loop

jac-cloud/jac_cloud/core/architype.py
To avoid conflict on enum check as hint might be a GenericAlias instance
=> [BUGFIX]: Add GenericAlias Check

jac/jaclang/compiler/parser.py
i edited walker_stmt,set_val,fstring,func_decl_params,tuple_val,type_ctx_block , multistring functions
=> [Parser-Refactor]-PR5

jac/jaclang/compiler/parser.py
Modified Functions
- lambda_expr
- atomic_call
- kw_pattern_list
- param_list
- class_pattern
- connect_op
- connect_to
- connect_from
- connect_any
- assignment
- tuple_list
=> [Parser-Refactoring] - 8th PR

jac/jaclang/compiler/parser.py
i edited fstr_parts,fstr_sq_patrs,filter_compare_item,filter_compare_list,has_assign_list,pattern_list,kw_expr_list,statement
=> [Parser-Refactor]-PR6

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py
=> Subnodelist removed from MatchArch

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py
=> SubNodelist removed from visit stmt

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py
=> Subnodelist removed from filtercompr

jac-mtllm/mtllm/plugin.py, jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/compiler/passes/tool/tests/test_unparse_validate.py
=> Remove SubNodeList from IterForStmt

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/compiler/passes/tool/tests/fixtures/myca_formatted_code/try_block_and_walker_spawn_and_fstrings.jac, jac/jaclang/tests/test_language.py
=> [SubnodeList-Remove] Removed from Try statement

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py
=> SubNodeList removed from TypedCtxBlock

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/import_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/sym_tab_build_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/tests/test_language.py
=> SubNodeList removed from Import

.github/workflows/test-jaclang.yml, jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/def_use_pass.py, jac/jaclang/compiler/passes/main/fuse_typeinfo_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/registry_pass.py, jac/jaclang/compiler/passes/main/sym_tab_build_pass.py, jac/jaclang/compiler/passes/main/tests/fixtures/mod_type_assign.jac, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/tests/test_language.py
=> Remove SubNodeList from Assignment

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py
=> SubNodeList removed from GlobalVars

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/pyjac_ast_link_pass.py
=> [GlobalStmt] Removing subnodelist from GlobalStmt

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/tests/test_language.py
=> Remove SubNodeList from If Elif Else statements 

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py
=> SubNodeList removed from AssignCompr

jac/jaclang/compiler/parser.py
Modified functions
- kw_expr
- list_val
- typed_filter_compare_list
- raise_stmt
- param_var
- name_list
- member_stmt
- typed_ctx_block
- abil_to_arch_chain
- arch_to_abil_chain
- arch_or_ability_chain
- arch_to_enum_chain
- assignment_list
- edge_ref_chain
- expr_list
=> [Parser-Refactoring] - 7th PR

jac/examples/reference/connect_expressions.py, jac/examples/reference/data_spatial_calls.py, jac/examples/reference/data_spatial_references.py, jac/examples/reference/data_spatial_spawn_expressions.py, jac/examples/reference/data_spatial_typed_context_blocks.py, jac/examples/reference/data_spatial_walker_statements.py, jac/examples/reference/disengage_statements.py, jac/examples/reference/ignore_statements.py, jac/examples/reference/visit_statements.py
=> Py Ref root() issue fixed

jac/support/jac-lang.org/docs/learning_section/jac_abilities/jac_abilities.md, jac/support/jac-lang.org/docs/learning_section/jac_architypes/jac_arch_abil_impl.md, jac/support/jac-lang.org/docs/learning_section/jac_architypes/jac_arch_abilities.md, jac/support/jac-lang.org/docs/learning_section/jac_architypes/jac_arch_attributes.md, jac/support/jac-lang.org/docs/learning_section/jac_architypes/jac_arch_inheritance_and_others.md, jac/support/jac-lang.org/docs/learning_section/jac_architypes/jac_architypes.md
=> Resolve incorrect paths of arch and abil

jac/examples/reference/architypes.py, jac/examples/reference/connect_expressions.py, jac/examples/reference/data_spatial_calls.py, jac/examples/reference/data_spatial_references.py, jac/examples/reference/data_spatial_spawn_expressions.py, jac/examples/reference/data_spatial_typed_context_blocks.py, jac/examples/reference/data_spatial_walker_statements.py, jac/examples/reference/disengage_statements.py, jac/examples/reference/ignore_statements.py, jac/examples/reference/special_comprehensions.py, jac/examples/reference/visit_statements.py, jac/jaclang/__init__.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/plugin/default.py, jac/jaclang/plugin/feature.py, jac/jaclang/plugin/spec.py, jac/jaclang/plugin/tests/test_jaseci.py, jac/jaclang/tests/test_language.py
| Before | After |
|--------|-------|
| ![image](https://github.com/user-attachments/assets/8b7958d8-aeff-495c-8cb4-f0c9111b241d) | ![image](https://github.com/user-attachments/assets/3fb9cd95-27ab-43df-821d-9a523ea60056) |
=> [WIP] jaclib architypes are decorators

jac/examples/micro/simple_walk_by_edge.jac, jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/jac.lark, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/plugin/tests/fixtures/simple_node_connection.jac, jac/jaclang/plugin/tests/fixtures/simple_persistent.jac, jac/jaclang/tests/fixtures/disconn.jac, jac/support/jac-lang.org/docs/for_coders/data_spatial/FAQ.md
=> filtering syntax refactored

jac/.pre-commit-config.yaml, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/utils/mypy_ast_build.py, jac/jaclang/langserve/utils.py, jac/jaclang/utils/treeprinter.py
=> upgrading mypy version in codebase to mypy v1.15.0

jac-mtllm/mtllm/plugin.py, jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/runtimelib/utils.py, jac/jaclang/tests/fixtures/chandra_bugs2.jac, jac/jaclang/tests/test_language.py
=> SubNodeList removed from  FuncCall

.github/workflows/test-jaclang.yml, jac/jaclang/compiler/compile.py, jac/jaclang/compiler/passes/main/__init__.py, jac/jaclang/compiler/passes/main/fuse_typeinfo_pass.py, jac/jaclang/compiler/passes/main/import_pass.py, jac/jaclang/compiler/passes/main/inheritance_pass.py, jac/jaclang/compiler/passes/main/schedules.py, jac/jaclang/compiler/passes/main/sym_tab_link_pass.py, jac/jaclang/compiler/passes/main/tests/test_import_pass.py, jac/jaclang/compiler/passes/main/tests/test_type_check_pass.py, jac/jaclang/compiler/symtable.py, jac/jaclang/langserve/engine.py, jac/jaclang/langserve/tests/test_server.py, jac/jaclang/tests/test_cli.py, jac/jaclang/tests/test_language.py, jac/jaclang/utils/treeprinter.py
=> Call PyImportPass from compile.py the same way JacImport is called

jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/ir_pass.py, jac/jaclang/compiler/passes/main/access_modifier_pass.py, jac/jaclang/compiler/passes/main/def_impl_match_pass.py, jac/jaclang/compiler/passes/main/def_use_pass.py, jac/jaclang/compiler/passes/main/import_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/pybc_gen_pass.py, jac/jaclang/compiler/passes/main/registry_pass.py, jac/jaclang/compiler/passes/main/tests/test_sub_node_pass.py, jac/jaclang/compiler/passes/main/type_check_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/compiler/passes/transform.py, jac/jaclang/compiler/passes/utils/mypy_ast_build.py, jac/jaclang/compiler/program.py, jac/jaclang/langserve/engine.py
=> refactor: small re-arch of passes and transforms

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/2-feature-request.md, .github/ISSUE_TEMPLATE/3-question-support.md, jac/jaclang/cli/cli.py, jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/ast_pass.py, jac/jaclang/compiler/passes/main/import_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/tests/test_decl_def_match_pass.py, jac/jaclang/compiler/passes/main/tests/test_import_pass.py, jac/jaclang/compiler/passes/main/tests/test_pyast_gen_pass.py, jac/jaclang/compiler/passes/main/tests/test_registry_pass.py, jac/jaclang/compiler/passes/main/tests/test_sub_node_pass.py, jac/jaclang/compiler/passes/main/tests/test_type_check_pass.py, jac/jaclang/compiler/passes/transform.py, jac/jaclang/compiler/program.py, jac/jaclang/compiler/tests/test_parser.py, jac/jaclang/langserve/engine.py, jac/jaclang/runtimelib/architype.py, jac/jaclang/runtimelib/feature.py, jac/jaclang/tests/test_bugs.py, jac/jaclang/tests/test_language.py
Making codebase architecture better.
=> code_arch: add error reporting to JacProgram and passthrough from transform

jac/jaclang/cli/cli.py, jac/jaclang/compiler/absyntree.py, jac/jaclang/compiler/codeloc.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/ast_pass.py, jac/jaclang/compiler/passes/main/import_pass.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/transform.py, jac/jaclang/compiler/program.py, jac/jaclang/compiler/tests/test_parser.py, jac/jaclang/runtimelib/importer.py, jac/jaclang/runtimelib/machine.py, jac/jaclang/tests/fixtures/deep_import_interp.jac, jac/jaclang/tests/test_language.py, jac/jaclang/utils/lang_tools.py, jac/jaclang/utils/test.py
=> feat: interp mode and final dest for annex

README.md
This pull request updates the `README.md` file to enhance the showcase of projects built with the Jaseci ecosystem. The changes improve the structure and presentation of the project list.
* Replaced the "Showcase Projects" section with a new "Awesome Jaseci Projects 🚀" section, featuring a table format for better readability and additional project details. This includes descriptions, links to GitHub repositories, and project websites.
=> Update Readme w/Showcase Projects

jac/jaclang/runtimelib/builtin.py, jac/jaclang/tests/fixtures/builtin_dotgen_json.jac, jac/jaclang/tests/test_cli.py, jac/jaclang/tests/test_language.py, jac/support/vscode_ext/jac/package-lock.json, jac/support/vscode_ext/jac/package.json, jac/support/vscode_ext/jac/src/extension.ts, jac/support/vscode_ext/jac/src/visual_debugger/index.html, jac/support/vscode_ext/jac/src/visual_debugger/visdbg.ts
=> Debug Visualizer

jac/support/vscode_ext/jac/README.md
This extension provides support for the [Jac](https://doc.jaseci.org) programming language. It provides syntax highlighting and leverages the LSP to provide a rich editing experience.
All that is needed is to have jac installed (i.e. `pip install jaclang`) and the `jac` command line tool present in your environment.
Note that it'll install [python extention for vscode](https://marketplace.visualstudio.com/items?itemName=ms-python.python) as a dependecy as it is needed to debug the python bytecode that jaclang produce.
To debug a jac file a launch.json file needs to created with the debug configurations. This can simply generated with:
1. Goto the debug options at the left pannel.
2. click "create a launch.json file"
3. Select `Jac Debug` Option
This will create a debug configration to run …
=> VSCode extension readme update after the debug vializar

jac/jaclang/compiler/annex.py, jac/jaclang/compiler/program.py
Moved .impl.jac and .test.jac annex parsing logic from program.py to a dedicated annex.py.
=> Extract and Refactor Annex Handling Logic

jac/support/jac-lang.org/docs/for_contributors/internals.md
=> docs: internals improved

jac/jaclang/cli/cli.py, jac/jaclang/cli/cmdreg.py, jac/jaclang/tests/test_cli.py
=> feat: improve cli help

jac/jaclang/compiler/passes/main/__init__.py, jac/jaclang/compiler/passes/main/annex_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/tests/fixtures/atest.impl.jac, jac/jaclang/compiler/passes/main/tests/fixtures/atest.jac, jac/jaclang/compiler/passes/main/tests/test_decl_impl_match_pass.py, jac/jaclang/compiler/program.py, jac/jaclang/tests/main.jac
=> fix: for walker statements not getting updated in annexes

.github/workflows/release-vsce.yml, jac/support/vscode_ext/jac/package.json
=> VSCE workflow and bump version to 0.35.0

.github/workflows/release-vsce.yml, jac/support/vscode_ext/jac/package.json
=> Update Version and Release to Marketplace

.github/workflows/release-vsce.yml, jac/support/vscode_ext/jac/package.json
=> Fix : VSCE is not updating the version

jac/jaclang/compiler/passes/main/def_use_pass.py, jac/jaclang/tests/fixtures/del_clean.jac, jac/jaclang/tests/test_cli.py
------------------------
Fix for the ; https://github.com/Jaseci-Labs/jaseci/issues/1822
=> Delete issue in jac-cloud

docs/docs/internals/planning_specs/native_type_system/lets_build.md, docs/mkdocs.yml, jac/jaclang/compiler/codeinfo.py, jac/jaclang/compiler/passes/tool/__init__.py, jac/jaclang/compiler/passes/tool/doc_ir.py, jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py, jac/jaclang/compiler/passes/tool/tests/test_doc_ir_gen_pass.py, jac/jaclang/utils/lang_tools.py
=> Better approach

jac/jaclang/compiler/codeinfo.py, jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
=> improvement to doc_ir_gen

jac/examples/reference/concurrent_expressions.jac, jac/examples/reference/concurrent_expressions.md, jac/examples/reference/concurrent_expressions.py, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/compiler/passes/tool/tests/test_unparse_validate.py, jac/jaclang/compiler/unitree.py, jac/jaclang/tests/fixtures/concurrency.jac, jac/jaclang/tests/test_language.py, jac/jaclang/utils/test.py
=> [hot fix] Concurrency 

README.md, docs/docs/learn/getting_started.md
- clean up license links
- restructure introduction with quick start
- add docs link
- `git status --short`
=> Improve main README

jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
- enhance whitespace cleanup by stripping nested trailing spaces before grouping
- `pre-commit run --files jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py` *(fails: command not found)*
- `PYTHONPATH=jac python jac/jaclang/cli/cli.py format jac/examples/manual_code/circle.jac --to_screen` *(fails: cannot import name 'override')*
=> Improve doc IR formatting

jac/jaclang/compiler/passes/main/pyast_load_pass.py
- refactor convert() to use handler lookup
- simplify extract_with_entry logic
- streamline proc_module and proc_function_def
- clarify augmented operator mapping
- `pip install pre-commit` *(fails: Could not find a version that satisfies the requirement pre-commit)*
- `pip install pytest` *(fails: Could not find a version that satisfies the requirement pytest)*
=> Improve cleanliness of pyast_load_pass

jac/jaclang/compiler/passes/main/pyast_load_pass.py
Reverts Jaseci-Labs/jaseci#1884
=> Revert "Improve cleanliness of pyast_load_pass"

.github/workflows/test-jaseci.yml, jac/examples/littleX/littleX.impl.jac, jac/examples/littleX/littleX.jac, jac/examples/littleX/littleX.test.jac
=> Add littleX to example folder and setup github action

jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/tests/test_language.py
=> update pyastloadpass for classdef

docs/docs/learn/introduction.md, docs/docs/learn/jac_in_a_flash.md, docs/mkdocs.yml, jac/examples/guess_game/guess_game4.impl.jac, jac/examples/guess_game/guess_game4.jac, jac/examples/guess_game/guess_game5.impl.jac, jac/examples/guess_game/guess_game5.jac, jac/jaclang/langserve/tests/test_server.py
- isolate implementation blocks into `guess_game4.impl.jac` and `guess_game5.impl.jac`
- update `jac_in_a_flash` tutorial with separate impl tabs
- adjust LSP test to use new impl file
- `pytest` *(fails: command not found)*
=> Split guess game impls

docs/docs/js/run-code.js, docs/scripts/mkdocs_serve.py
* **File Watching and Automatic Rebuilds**: Introduced a new `DebouncedRebuildHandler` class using `watchdog` to monitor file changes and trigger debounced rebuilds of the MkDocs site. This ensures efficient rebuilds without excessive triggers during rapid changes.
* **Custom HTTP Server**: Replaced the `serve_with_headers` function with `serve_with_watch`, which integrates file watching and starts the MkDocs server with custom security headers.
=> Updated Mkdocs Server starting Script for Auto Reloading

docs/docs/learn/data_spatial/sample_code/DSP.jac, docs/docs/learn/examples/littleX/src/littleX.impl.jac, docs/docs/learn/examples/rag_chatbot/solution/server.jac, jac/examples/littleX/littleX.impl.jac, jac/examples/micro/access_info.jac, jac/examples/micro/basic_class.jac, jac/examples/micro/basic_class_pylike.jac, jac/examples/micro/free_code.jac, jac/examples/micro/no_here.jac, jac/examples/micro/separate_defs.jac, jac/examples/micro/type_hints.jac, jac/examples/micro/wierd_syntax.jac, jac/examples/reference/concurrent_expressions.jac, jac/examples/rpg_game/jac_impl/jac_impl_6/main.impl/level.impl.jac, jac/examples/rpg_game/jac_impl/jac_impl_6/main.impl/start_screen.impl.jac, jac/jaclang/compiler/passes/main/def_use_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/tests/fixtures/symtab_link_tests/action/actions.jac, jac/jaclang/compiler/passes/main/tests/fixtures/symtab_link_tests/main.jac, jac/jaclang/compiler/tests/fixtures/fam.jac, jac/jaclang/compiler/unitree.py, jac/jaclang/tests/fixtures/concurrency.jac, jac/jaclang/tests/fixtures/guess_game.jac, jac/jaclang/tests/fixtures/here_usage_error.jac, jac/jaclang/tests/fixtures/here_visitor_usage.jac, jac/jaclang/tests/test_language.py
=> implement visitor keyword in backend

docs/docs/extra.css, docs/docs/js/run-code.js, docs/mkdocs.yml
* Replaced the previous editable `pre` block with an embedded Monaco editor for improved code editing.
* Updated CSS selectors from `.code-container` to `.code-block` for consistency and alignment with the new structure.
=> Replaced the textarea of code-block with monaco editor

jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/runtimelib/machine.py, jac/jaclang/tests/fixtures/backward_edge_visit.jac, jac/jaclang/tests/test_language.py
=> [Fix] Edge backward traversal

jac/support/vscode_ext/jac/package-lock.json, jac/support/vscode_ext/jac/src/environment/manager.ts, jac/support/vscode_ext/jac/src/extension.ts, jac/support/vscode_ext/jac/tsconfig.tsbuildinfo
------
Files were missed in the previous PR because the folder was named `env` and ignored. Renamed to `environment `and committed properly.
and test will be added
=> [VSCE] : Include Missed Environment Directory

docs/docs/learn/jac-cloud/async_walker.md, docs/docs/learn/jac-cloud/deployment.md, docs/docs/learn/jac-cloud/env_vars.md, docs/docs/learn/jac-cloud/introduction.md, docs/docs/learn/jac-cloud/logging.md, docs/docs/learn/jac-cloud/permission.md, docs/docs/learn/jac-cloud/quickstart.md, docs/docs/learn/jac-cloud/scheduler.md, docs/docs/learn/jac-cloud/webhook.md, docs/docs/learn/jac-cloud/websocket.md, docs/mkdocs.yml
=> [WIP] Jac Cloud Doc Organize

jac/jaclang/compiler/jac.lark, jac/jaclang/compiler/parser.py, jac/jaclang/compiler/passes/main/def_use_pass.py, jac/jaclang/compiler/passes/main/pyast_gen_pass.py, jac/jaclang/compiler/passes/main/tests/test_cfg_build_pass.py, jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py, jac/jaclang/compiler/tests/test_parser.py, jac/jaclang/compiler/unitree.py, jac/jaclang/tests/test_language.py
=> figured out how to get rid of subnodelist

docs/docs/extra.css, docs/docs/learn/introduction.md
=> refactor: Enhance introduction with clearer DSP concepts and examples

docs/docs/js/jac.monarch.js, docs/docs/js/run-code.js, docs/mkdocs.yml
* Replaced the `MutationObserver` with an `IntersectionObserver` to lazily initialize code blocks only when they are visible in the viewport. This improves performance by avoiding unnecessary initialization of off-screen elements. 
* Added a `WeakSet` (`initializedBlocks`) to track already initialized code blocks and prevent redundant setups.
* Disabled the minimap in Monaco Editor to simplify the user interface.
---
- **Monaco Editor's Native Support:**  
Monarch is the built-in, native tokenization and syntax highlighting system of Monaco Editor. It integrates seamlessly without additional dependencies or complex setups.
- **Better Asynchronous Integration:**  
Monaco Editor loads and initializes asynchronously via AMD modules (especially when using CDN). Monarch tokenizers are designed …
=> Custom div Lazy loading and Syntax Highlighting

docs/docs/learn/examples/mtp_examples/fantasy_trading_game.md, docs/mkdocs.yml, jac-mtllm/examples/fantasy_trading_game.jac
Documentation for the bellow game that contains example to use tool call with `ReAct` method.
=> MTLLM game documentation added

jac/examples/reference/assignments.jac, jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py, jac/jaclang/compiler/passes/tool/jac_formatter_pass.py, jac/jaclang/compiler/passes/tool/tests/fixtures/general_format_checks/triple_quoted_string.jac, jac/jaclang/compiler/passes/tool/tests/fixtures/simple_walk_fmt.jac, jac/jaclang/compiler/passes/tool/tests/fixtures/tagbreak.jac, jac/jaclang/compiler/passes/tool/tests/test_jac_format_pass.py, jac/jaclang/langserve/sem_manager.jac, jac/jaclang/tests/fixtures/arch_rel_import_creation.jac, jac/jaclang/tests/fixtures/create_dynamic_archetype.jac, jac/jaclang/tests/test_language.py, jac/jaclang/tests/test_reference.py
=> attempting improvements on formatter

jac/jaclang/langserve/engine.jac, jac/jaclang/langserve/tests/server_test/test_lang_serve.py, jac/jaclang/langserve/tests/server_test/utils.py
Ensures  per-file syntax build handling to stabilize highlighting.
=> [VSCE]: Fix: Multi-File SemToken Stability

docs/scripts/mkdocs_serve.py, jac/jaclang/compiler/passes/main/tests/test_import_pass.py, jac/jaclang/compiler/program.py, jac/jaclang/tests/test_language.py
=> refactor: program better

docs/docs/jac_book/chapter_7.md
=> [JacBookFix] Chapter 7

docs/docs/js/run-code.js, docs/mkdocs.yml
=> Open playground in a new tab

docs/docs/learn/jac-mtllm/model_declaration.md, docs/docs/learn/jac-mtllm/python_integration.md, docs/docs/learn/jac-mtllm/quickstart.md, docs/docs/learn/jac-mtllm/usage.md
=> MTLLM documentation updated and issues were fixed

docs/docs/extra.css, docs/docs/index.html
=> generalizing theme slickness

docs/docs/extra.css
=> Update header color to white for better visibility

jac-mtllm/scripts/gh_release.py, jac/jaclang/compiler/codeinfo.py, jac/scripts/gh_release.py
=> linting fixed

docs/docs/learn/examples/mtp_examples/rpg_game.md, docs/mkdocs.yml
The game level generator example rewrite to be more appealing.
=> [Docs] Rewrite Game level generator example as a walkthrough

docs/docs/jac_book/chapter_3.md
=> Chapter3 fix

docs/docs/jac_book/chapter_11.md
=> [JacBookFix] Chapter 11

docs/docs/jac_book/chapter_12.md
=> [JacBookFix] Chapter 12

docs/docs/jac_book/chapter_4.md
=> chapter 4 

docs/docs/jac_book/chapter_2.md
=> [Refactor] Chapter 2

docs/docs/jac_book/chapter_8.md
=> [Refactor] Chapter 8

docs/docs/jac_book/chapter_9.md
=> [Refactor] Chapter 9

jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
=> Formatter within method

docs/docs/learn/data_spatial/filtering.md, docs/docs/learn/data_spatial/nodes_and_edges.md, docs/docs/learn/data_spatial/sequence.md, docs/docs/learn/data_spatial/walkers.md, jac/examples/data_spatial/create_node.jac, jac/examples/data_spatial/edge_filtering.jac, jac/examples/data_spatial/filtering.jac
=> Object Spatial Docs updated

docs/docs/learn/jac-mtllm/quickstart.md, docs/docs/learn/jac-mtllm/usage.md
=> Update function definitions to use parentheses for AI integration

jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py, jac/jaclang/langserve/engine.jac
=> Improving fmt

docs/docs/jac_book/chapter_5.md
Clarify the separation of implementation and interface in Jac, and introduce a detailed workflow for import resolution to improve understanding and usability.
=> Enhance chapter 5 with implementation details and import resolution workflow

docs/docs/communityhub/release_notes.md, jac/jaclang/runtimelib/machine.py, jac/jaclang/tests/fixtures/spawn_loc_list.jac, jac/jaclang/tests/test_language.py
=> Spawn list of nodes, edges

docs/docs/jac_book/chapter_1.md, docs/docs/jac_book/chapter_10.md, docs/docs/jac_book/chapter_11.md, docs/docs/jac_book/chapter_2.md, docs/docs/jac_book/chapter_3.md, docs/docs/jac_book/chapter_4.md, docs/docs/jac_book/chapter_6.md, docs/docs/jac_book/chapter_7.md, docs/docs/jac_book/chapter_8.md, docs/docs/jac_book/chapter_9.md
=> Jacbook refactor various fixes

docs/docs/learn/jac-cloud/introduction.md, docs/docs/learn/jac-cloud/quickstart.md
Added installation instructions to the 5-minute Intro.
=> [Jac-Cloud Docs] Quick Fix

docs/docs/learn/examples/littleX/src/example_game.jac, jac-mtllm/mtllm/aott.py, jac-mtllm/mtllm/llms/anthropic.py, jac-mtllm/mtllm/llms/base.py, jac-mtllm/mtllm/llms/fake.py, jac-mtllm/mtllm/llms/google.py, jac-mtllm/mtllm/llms/groq.py, jac-mtllm/mtllm/llms/huggingface.py, jac-mtllm/mtllm/llms/ollama.py, jac-mtllm/mtllm/llms/openai.py, jac-mtllm/mtllm/llms/togetherai.py, jac-mtllm/mtllm/plugin.py, jac-mtllm/pyproject.toml, jac/jaclang/compiler/passes/main/pyast_gen_pass.py
Currently the retry mechanism isn't working properly and every time it does a retry, it'll always fail so, I have remove it completely and we'll add it back at the end of the series of pr,
=> 🛠️ MTLLM Structured output + Tool calling (refactor)

docs/docs/index.html
=> update landing page

docs/docs/jac_book/chapter_12.md, docs/docs/jac_book/chapter_13.md
- Merged chapter 14 into 12 since they both cover the same content
- Fixed bugs in the examples
- Expanded on some of the explanations for the examples.
=> Rf jackook 3 fix

docs/docs/learn/examples/littleX/full_guide.md, docs/docs/learn/examples/littleX/tutorial.md
=> [Fix] Example doc fixes

docs/docs/index.html
=> Update discord link

docs/docs/jac_book/chapter_14.md, docs/docs/jac_book/chapter_15.md, docs/docs/jac_book/chapter_16.md, docs/docs/jac_book/chapter_17.md, docs/docs/jac_book/chapter_18.md, docs/docs/jac_book/chapter_19.md, docs/docs/jac_book/chapter_20.md
=> [Jacbook refactor] Refactor fixes

docs/docs/index.html, docs/mkdocs.yml
=> internals moved to community

jac-mtllm/mtllm/__init__.py, jac-mtllm/mtllm/llm.py, jac-mtllm/mtllm/types.py, jac-mtllm/tests/fixtures/streaming_output.jac, jac-mtllm/tests/test_mtllm.py
```py
import from mtllm { Model }
glob llm = Model(model_name="gpt-4o-mini");
""" Generate short essay (less than 300 words) about the given topic """
def generate_essay(topic: str) -> str by llm(stream=True);
with entry {
topic = "The orca whale and it's hunting techniques";
for tok in generate_essay(topic) {
print(tok, end='', flush=True);
}
print();
}
```
=> 🚅 Streaming token implementation for mtllm

jac-mtllm/README.md
=> [MTLLM]Fixed minor error in README

docs/docs/communityhub/release_notes.md, jac/examples/littleX/littleX.impl.jac, jac/examples/littleX/littleX.test.jac, jac/jaclang/runtimelib/builtin.py, jac/jaclang/runtimelib/machine.py, jac/jaclang/runtimelib/memory.py
=> Implement get_all_root builtin method

jac/support/vscode_ext/jac/src/commands/index.ts, jac/support/vscode_ext/jac/src/environment/manager.ts, jac/support/vscode_ext/jac/src/utils/jacRunner.ts, jac/support/vscode_ext/jac/src/visual_debugger/visdbg.ts, jac/support/vscode_ext/jac/src/webview/visualDebugger.ts
Before
--------
After: Jac path(Full) properly Utilized
-------
=> [VSCE] VisDebug support for windows

jac/support/vscode_ext/jac/package-lock.json, jac/support/vscode_ext/jac/src/commands/index.ts, jac/support/vscode_ext/jac/src/constants.ts, jac/support/vscode_ext/jac/src/environment/manager.ts, jac/support/vscode_ext/jac/src/utils.ts, jac/support/vscode_ext/jac/src/utils/envDetection.ts
--------
- Added deeper search into subdirectories
- Cached discovered environments to prevent repeated scans
- Trigger re-scan only on manual refresh
-----
https://github.com/user-attachments/assets/e1159b93-74af-410f-985f-1789e9d879e3
=> [VSCE] Implement cached environment detection with deeper directory scanning

.github/ISSUE_TEMPLATE/1-bug-report.md, .github/ISSUE_TEMPLATE/4-docs.md
=> 📚 Add documentation issue template for improvements and issues

docs/docs/extra.css, docs/docs/js/feedback.js, docs/mkdocs.yml
Added feedback in each page. Connected to G Sheet
Appears when 95% of the page reached when scrolling.
Hovering Over and Selection
=> feedback buttons added

docs/docs/communityhub/release_notes.md, docs/docs/learn/jac-cloud/utilities.md, docs/mkdocs.yml, jac-cloud/jac_cloud/jaseci/main.py, jac-cloud/jac_cloud/jaseci/routers/__init__.py, jac-cloud/jac_cloud/jaseci/routers/utils.py, jac-cloud/jac_cloud/jaseci/security/__init__.py, jac-cloud/jac_cloud/tests/openapi_specs.yaml, jac-cloud/jac_cloud/tests/test_simple_graph.py
```json
{
"edges": [
{
"id": "e::68829d45d025ccb2469a2dbd",
"source": "n::68829d23d025ccb2469a2d93",
"target": "n:A:68829d45d025ccb2469a2db8"
},
{
"id": "e::68829d45d025ccb2469a2dba",
"source": "n:A:68829d45d025ccb2469a2db8",
"target": "n:B:68829d45d025ccb2469a2db9"
},
{
"id": "e::68829d45d025ccb2469a2dbc",
"source": "n:B:68829d45d025ccb2469a2db9",
"target": "n:C:68829d45d025ccb2469a2dbb"
}
],
"nodes": [
{
"id": "n::68829d23d025ccb2469a2d93",
"edges": [
"e::68829d45d025ccb2469a2dbd"
]
},
{
"id": "n:A:68829d45d025ccb2469a2db8",
"edges": [
"e::68829d45d025ccb2469a2dba",
"e::68829d45d025ccb2469a2dbd"
]
},
{
"id": "n:B:68829d45d025ccb2469a2db9",
"edges": [
"e::68829d45d025ccb2469a2dba",
"e::68829d45d025ccb2469a2dbc"
]
},
{
"id": "n:C:68829d45d025ccb2469a2dbb",
"edges": [ …
```
=> [JAC-CLOUD]: Util APIs

docs/docs/learn/jac-lens.md
UI Changed
images one after the other
2x2
=> jac-lens document updated

docs/docs/communityhub/release_notes.md, jac-cloud/pyproject.toml, jac-mtllm/pyproject.toml, jac/pyproject.toml
=> version pump jaclang 0.8.5 cloud 0.2.5 mtllm 0.4.0

jac-mtllm/mtllm/llm_connector.py, jac-mtllm/pyproject.toml
Closes: https://github.com/jaseci-labs/jaseci/issues/2527
=> 🤖 Litellm drop unsupported parameters (for gpt-5) added

docs/docs/learn/examples/littleX/src/littleX.impl.jac, docs/docs/learn/examples/littleX/src/littleX.jac, docs/docs/learn/examples/littleX/tutorial.md
Fix the issues in the littleX documentation
=> LittleX source file numbers updated in documentation

jac/support/vscode_ext/jac/syntaxes/jac.tmLanguage.json
=> Add syntax highlighting for sem keyword in Jac VSCE

docs/mkdocs.yml
Jac Lens section re located to Jac Cloud Section
=> relocating jac lens

docs/docs/index.html, docs/docs/landing.css
=> logos changed - smaller

jac/jaclang/langserve/dev_engine.jac, jac/jaclang/langserve/engine.jac, jac/jaclang/langserve/tests/test_dev_server.py
=> LSP Hover support and LSP tests

jac/jaclang/langserve/engine.jac, jac/jaclang/langserve/tests/server_test/test_lang_serve.py
=> Integrate New Type Checking into VSCE

jac-splice-orc/jac_splice_orc/plugin/splice_plugin.py, jac/jaclang/cli/cli.py, jac/jaclang/runtimelib/importer.py, jac/jaclang/runtimelib/machine.py, jac/jaclang/tests/fixtures/py_run.jac, jac/jaclang/tests/fixtures/py_run.py, jac/jaclang/tests/test_cli.py
=> Infer Language from cmd

jac/jaclang/cli/cli.py, jac/jaclang/compiler/passes/main/pyast_load_pass.py, jac/jaclang/compiler/passes/main/tests/test_cfg_build_pass.py, jac/jaclang/compiler/unitree.py, jac/jaclang/runtimelib/importer.py, jac/jaclang/runtimelib/machine.py, jac/jaclang/tests/fixtures/pyfunc.py, jac/jaclang/tests/test_cli.py
=> String Representation Issue

docs/docs/assets/examples/basic/gradeBook_object.jac, docs/docs/assets/examples/basic/pet_records_with_access_control.jac, docs/docs/assets/examples/object_spatial/family_relationship_graph.jac, docs/docs/assets/examples/object_spatial/finding_common_interests.jac, docs/docs/assets/examples/object_spatial/greeting_friends_walker.jac, docs/docs/playground/jac_examples.json
=> Adding examples to playground step 1

jac/examples/guess_game/guess_game1.jac
The preivous guesgame1.jac didn't work. Fixed the isue.
=> guessgame 1 issue fixed

docs/docs/index.html, docs/docs/landing.css, docs/mkdocs.yml
=> Add Jac GPT link and enhance affiliations section with descriptions

docs/docs/index.html, docs/docs/js/landing.js
OOP changed to OSP
Summary to OSP addded
=> What is Jac | OOP converted to OSP and the summary was added

docs/docs/communityhub/release_notes.md, jac-byllm/deprecation/pyproject.toml, jac-byllm/pyproject.toml, jac-cloud/pyproject.toml, jac/pyproject.toml
=> 🔖 bump_versions_for_release (jaclang 0.8.7, jac-cloud 0.2.7, byllm 0.4.2)

jac/jaclang/compiler/passes/main/tests/fixtures/checker_self_type.jac, jac/jaclang/compiler/passes/main/tests/test_checker_pass.py, jac/jaclang/compiler/passes/main/type_checker_pass.py, jac/jaclang/compiler/type_system/type_evaluator.py, jac/jaclang/compiler/type_system/types.py
=> 📦 Self type resolve

docs/jac_syntax_highlighter.py
=> sem syntax highlight

docs/docs/learn/jac-byllm/multimodality.md, docs/docs/learn/jac-byllm/python_integration.md, docs/docs/learn/jac-byllm/usage.md
=> Semstring Documentation fo Python Mode

docs/docs/learn/jac-byllm/with_llm.md, docs/mkdocs.yml, jac-byllm/README.md
=> Byllm_Landing page Update

docs/docs/learn/jac-byllm/with_llm.md
=> Bug Fixes and Tweaks on ByLLM Docs Main Page

docs/docs/learn/examples/mtp_examples/rpg_game.md
Did some twaks for RPG ggame tutorial.
=> RPG game tutorial change

jac/support/vscode_ext/jac/src/environment/manager.ts, jac/support/vscode_ext/jac/src/extension.ts, jac/support/vscode_ext/jac/src/lsp/client.ts, jac/support/vscode_ext/jac/src/utils.ts, jac/support/vscode_ext/jac/src/utils/envDetection.ts
if proper env(where jac installed)  is not selected at initial state or jac is removed from that env , this error pop up.
=> 🐛 Fix startup validation errors

jac/support/vscode_ext/jac/package.json
=> 🚀 Release VSCode ext v2025.9.24

jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py, jac/jaclang/compiler/passes/tool/tests/fixtures/tagbreak.jac, jac/jaclang/tests/test_language.py
=> Fix the issue of extra spaces in index slice

jac-byllm/examples/agentic_ai/task_manager.jac
Implemented the task manager lite version to add as an example for byLLM
=> Byllm examples task manager lite version

docs/docs/learn/examples/littleX/tutorial.md, docs/mkdocs.yml
=> Docs update

jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py, jac/jaclang/compiler/passes/tool/tests/fixtures/tagbreak.jac, jac/jaclang/tests/test_language.py
Fix removing extra white space in decorator formatting
=> Fix decorator formatting in classes and functions

docs/docs/communityhub/release_notes.md, jac-byllm/deprecation/pyproject.toml, jac-byllm/pyproject.toml, jac-cloud/pyproject.toml, jac/pyproject.toml
=> ⬆️ Version Bump: 0.8.8 / 0.2.8 / 0.4.3

docs/docs/learn/beginners_guide_to_jac.md, docs/docs/learn/superset_python.md, docs/mkdocs.yml
=> better docs

docs/docs/communityhub/release_notes.md, docs/docs/internals/plugin_system_guide.md, docs/mkdocs.yml, jac-byllm/byllm/hooks_metadata.py, jac-byllm/pyproject.toml, jac-cloud/jac_cloud/plugin/hooks_metadata.py, jac-cloud/pyproject.toml, jac-streamlit/jaclang_streamlit/hooks_metadata.py, jac-streamlit/pyproject.toml, jac/jaclang/__init__.py, jac/jaclang/cli/cli.py, jac/jaclang/runtimelib/lazy_plugins.py, jac/jaclang/runtimelib/machine.py
=> Plugin arch revamp
