- docs/docusaurus.config.js
- docs/src/pages/index.js
Add the following links to documentation website:
**Docs** --> /docs/intro
**GitHub** --> https://github.com/Jaseci-Labs/jaseci
**GitHub Discussions** --> https://github.com/Jaseci-Labs/jaseci/discussions
**Jaseci.org** --> https://www.jaseci.org/
See screenshot below:
> Links update

- support/vscode_extension/jac/syntaxes/jac.tmLanguage.json
Here is my attempt to address missing keywords and patterns for VSCode syntax highlighting.
Highlight the following keywords:
> Syntax highlight update

- support/monitoring/README.md
- support/monitoring/grafana/grafana.yaml
I think that at this point, the document has completely given up teaching people to establish prometheus in a namespace. 
Fix:
1. Deleted '-n prometheus' param in the commands given completely.
2. \<xxx\> is considered a macro substitution in markdown and we did not define \<namespace\> macro. So it is ignored. I replaced it with \\\<namespace\\\> and added some comments about the usage.
> Fix: namespace problem in monitoring document

- docs/docs/jsctl/a-simple-workflow-for-tinkering.md
- docs/docs/your-first-jac-program/adding-an-ai-component.md
1. It seems that the `walker run -name` command has deprecated so I fixed it.
2. Deleted a duplicated part ( a mistake ).
> Fix: walker run command  Delete: a duplicated part in Adding an AI Component

- docs/jaseci-docs.yaml
Allocate more memory to the node process for jaseci docs
The node process of jaseci docs run out of memory when compiling the latest version of  the docs.
No
No
No
> Allocate more memory to the node process for jaseci docs

- jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
- jaseci_serv/jaseci_serv/jac_api/tests/zsb.jac
- jaseci_serv/jaseci_serv/jac_api/views.py
- File type field will now be able to access via `has fieldName`
- Update file parser to be able to read large file
N/A
Nope, tho I have added unit tests for different multipart scenarios
Slightly, file type field will now be accessible via `has fieldName` instead of using `global.info["request_context"]["body"]["fieldName"]`
multipart/form-data approach with files
> [MULTIPART-FORMDATA-ENHANCEMENT]: Allow file type field to be access using `has fieldName`

- jaseci_core/jaseci/jac/interpreter/interp.py
- jaseci_core/jaseci/jac/machine/machine_state.py
- jaseci_core/jaseci/tests/test_jac.py
- jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
- jaseci_serv/jaseci_serv/jac_api/tests/zsb.jac
- Added TryException class to improved Try/Else backtracking
- Removal of default exception handling on actions trigger interp to enable Try/Else on jaseci actions
N/A
Yes, you can now use Try/Else on Jaseci Actions
No, It's supposed to be an improvement for Try/Else backtracking
Yes, Try/Else can now determine the exact line of the error.
Jaseci Actions now throws exception to be handled on Jac side
Jaseci Actions, the removal of exception handling might need changes on current/existing jac projects since exception should be handled "mandatorily" instead of having fix handling
> [TRY-ELSE]: Improve exception backtracking when using Try/Else

- support/vscode_extension/jac/syntaxes/jac.tmLanguage.json
Regex no longer necessary; breaks syntax highlighting.
> fix: remove unnecessary match regex

- jaseci_core/jaseci/api/graph_api.py
- jaseci_core/jaseci/graph/edge.py
- jaseci_core/jaseci/graph/graph.py
- jaseci_core/jaseci/graph/node.py
- jaseci_core/jaseci/jsctl/tests/test_jsctl.py
Dot mode now have `detailed` param. Default dot mode will now include the label only. Detailed dot mode will include every attributes of the node/edge
N/A
Yes, Unit test for `dot` is now updated
Yes, existing graph_get should now have `detailed: true` but if they doesn't use the node/edge attributes it should work fine
Yes, existing graph_get usage
> [FEATURE-REQUEST]: Simplified Dot

- support/monitoring/README.md
- support/monitoring/grafana-dashboards/KubernetesPodMetrics.json
Add a Grafana dasboard that can monitor pods.
Exported Grafana Dashboards.
> feat(support.monitoring.grafana): add a grafana dashboard

- .github/workflows/jaseci_kit_test.yml
Currently, we allow the jskit pipeline to fail because sometimes github action will run out of memory when executing tests. We have resolved this and this PR will make jskit pipeline success a requirement **for any PRs that updates files in `jaseci_kit/`**
> Make jskit CI pipeline mandatory again

- jaseci_serv/jaseci_serv/jaseci_serv/settings.py
Celery default broker_url should use the same redis config
N/A
No
No
N/A
> [CELERY-CONIG]: Adjust celery config to use redis config

- jaseci_core/jaseci/graph/edge.py
- jaseci_core/jaseci/graph/node.py
graph will now only include the id when detailed is true
N/A
No
Maybe? I'm not sure if "id" in dot is used on any 3rd party graph viewer
Dot
> [GRAPH-GET]: Only include the id when detailed is true

- .github/workflows/python-publish.yml
Add `--skip-existing` flag to the pypi package publishing workflow. This will allow us to publish individual pypi projects without requiring a tagging up all three packages.
@marsninja this is needed for a particular reason. we can discuss if this is what we want long term. It will be very easy to change it back if we decide this is not good.
> Allow of pypi publishing of individual projects

- examples/CanoniCAI/CCAI_codelab.md
Changing CanoniCAI Init Walker DOT graph representation typo. The node n1 has type"faq_state" when it should have type "faq_root" (as the diagram below designates).
This will enhance understanding of DOT lanugage syntax and the code-along instructions as it remedies a typo that directly affects new users.
> Fixing CCAI_codelab DOT language graph n1 type: faq_state --> faq_root

- jaseci_core/jaseci/api/queue_api.py
- jaseci_core/jaseci/svc/task/README.md
- jaseci_core/jaseci/svc/task/task.py
- jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
- new api for get task by id with wait
N/A
Yes, existing unit test is adjusted
No
N/A
> [MINOR]: Adding get task api with wait option

- README.md
Fixing all instances of "graphiz" in the README.md to "graphviz" since Graphviz is the actual graphing python library. 
No related issue
No feature being added or changed
This would not impact Jaseci users. It would just remove typos in the README so that it's clear that Graphviz is the actual library being used
No, just 10 same typo fixes in the pull request
> Fix graphiz to graphviz in README.md

- examples/CanoniCAI/CCAI_codelab.md
The walker run command was originally: walker run talk -ctx {\"question\": \"I want to schedule a test drive\"}
The command does not run as is, instead resulting in the following: Error: Got unexpected extra arguments ("I want to schedule a test drive"}). 
This is fixed by adding outer quotation marks around the brackets (as is consistent with the other -ctx arguments across the tutorial).
> fixed walker run command (missing quotes)

- examples/CanoniCAI/CCAI_codelab.md
Fixed a simple typo in the multi-file section for the CanoniCAI section.
This does not relate to a currently created issue.
No testing required.
This will not affect the user in any way other than easier readability.
> Fix typo in Multi-file section

- jaseci_core/jaseci/api/queue_api.py
- jaseci_core/jaseci/svc/task/config.py
- jaseci_core/jaseci/svc/task/task.py
- jaseci_core/jaseci/tests/test_progs.py
- Added timeout for AsyncResult.get
- Adjust unit test to cover changes
current github workflow stuck on unit test
Yes, unit test adjusted
No
Github workflows
> [TASK]: Add on wait result timeout

- jaseci_core/jaseci/actions/live_actions.py
`## Describe your changes
Try to unload an action (or actionset) that is previous loaded via remote URL causes the following failure and exception.
```
@jaseci > actions unload actionset use
{
"response": "Internal Exception: 'js_remote_hook'",
"success": false,
"errors": [
"Internal Exception: 'js_remote_hook'"
],
"stack_trace": "Traceback (most recent call last):\n  File \"/jaseci/jaseci_core/jaseci/api/interface.py\", line 193, in general_interface_to_api\n    ret = getattr(_caller, api_name)(**param_map)\n  File \"/jaseci/jaseci_core/jaseci/api/actions_api.py\", line 199, in actions_unload_actionset\n    return {\"success\": lact.unload_actionset(name)}\n  File \"/jaseci/jaseci_core/jaseci/actions/live_actions.py\", line 134, in unload_actionset\n    unload_action(i)\n  File …
```
> Fix unload action for remote loaded actions

- jaseci_core/jaseci/api/graph_api.py
- jaseci_core/jaseci/api/tests/test_graph_api.py
- jaseci_core/jaseci/graph/graph.py
- jaseci_core/jaseci/graph/node.py
- jaseci_core/jaseci/jsctl/tests/test_jsctl.py
- jaseci_core/jaseci/tests/test_jac.py
- jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
- Allow node as entry point for graph get
- Refactor for traversing
- Adjust unit test to cover changes
N/A
Yes, unit test are adjusted to cover changes
No
Graph get
> [GRAPH-GET]: Allow Node entry instead of Graph; Some refactor for traversing

- jaseci_core/jaseci/actions/standard/tests/fixtures/webtool.jac
- jaseci_core/jaseci/actions/standard/tests/test_webtool.py
- jaseci_core/jaseci/actions/standard/webtool.py
Some URL's doesn't allow metadata scrapping, it's returning a forbidden error (403) response.
Added user-agent header to `metadata_parser.MetadataParser` call.
> Fix: Webtool returning a forbidden error response.

- jaseci_serv/jaseci_serv/jac_api/views.py
- This is to avoid conflict when django url variable has the same name with the request body. This will save the request body first before merging with django url variable
N/A
No
No
Request context
> [MINOR]: Allow to save the actual request body before merging with request url mapping

- jaseci_serv/jaseci_serv/jsx_oauth/HOWTO.md
- jaseci_serv/jaseci_serv/jsx_oauth/config.py
- jaseci_serv/jaseci_serv/jsx_oauth/models.py
- jaseci_serv/jaseci_serv/jsx_oauth/utils.py
- jaseci_serv/templates/examples/social_auth.html
- Add support on manual set on callback_url from FE
- Added Facebook sample integration
- Some refactor
N/A
No
No
Social Login
> [SOCIALAUTH]: Update and Refactor

- examples/CanoniCAI/codelabs/2_faq.md
[sidganti](https://github.com/sidganti) commented [7 minutes ago](https://github.com/Jaseci-Labs/jaseci/pull/867#issue-1561659324)
The white now removed whitespaces makes violated bash syntax.
Now, it will be easier for individuals to copy the command into their terminal without having to manually diagnose and fix this.
Error the old line returned :
ERROR: Invalid requirement: 'jac_nlp[use_qa,'
> Fix command for example in 2_faq.md

- examples/CanoniCAI/codelabs/2_faq.md
This PR is a docs fix addressing the pip commands in Section 2. When installing modules and wanting to specify optional dependencies to install, you need the module and brackets surrounded in quotations. This should fix the commands so students in the future are not confused.
> docs: update pip commands in Section 2

- jaseci_core/jaseci/jsctl/jsctl.py
- jaseci_core/jaseci/jsorc_settings.py
- jaseci_serv/jaseci_serv/__init__.py
Also, temporarily suppress the warning messages from initializing redis service and task service because local jsserv logs are unusable because of it.
> Hotfix: jsctl remote calls bug

- jaseci_serv/jaseci_serv/jsx_oauth/config.py
- jaseci_serv/jaseci_serv/jsx_oauth/tests/test_social_auth.py
Removing django.contrib.sites to removed the issue on clean build.
Also, we don't use the sites validation anymore in jsx-auth
> [HOTFIX]: Removing django.contrib.sites

- jaseci_core/jaseci/jac/machine/jac_value.py
- jaseci_core/jaseci/tests/jac_test_progs.py
- jaseci_core/jaseci/tests/test_progs.py
Scenario:
```js
node c {
has c1, c2;
}
walker b {
has anchor b1, b2;
with entry {
report b1;
report b2;
}
}
walker a {
has a1;
with entry {
a2 = null;
// this will not return errors as we always initialize node before assigning the arguments
te = spawn here ++> node::c(c1=a1, c2=a2);
// this will return errors since it will reference b1 in walker b even it's not yet present
te = spawn here walker::b(b1 = a1, b2 = a2);
}
}
#response
{
"success": false,
"report": [
null,
null
],
"final_node": "urn:uuid:dcee518d-ee0e-439d-9d60-230b3c4cfd4d",
"yielded": false,
"errors": [
"testing:a - line 18, col 34 - rule spawn_assign - Key b1 not found in object/dict.",
"testing:a - line 18, col 43 - rule spawn_assign - Key b2 not found in object/dict."
]
}
```
I haven't fully understand the behavior but …
> [BUGFIX]: Allow none assignment on spawn walker

- jaseci_core/jaseci/actions/live_actions.py
- jaseci_core/jaseci/actions/tests/test_actions.py
Fix an issue where using kwargs for remote action call do not use default value set in the action definition
> Remote action call kwargs fix

- jaseci_core/jaseci/extens/act_lib/tests/fixtures/webtool.jac
- jaseci_core/jaseci/extens/act_lib/tests/test_webtool.py
- jaseci_core/jaseci/extens/act_lib/webtool.py
- jaseci_core/setup.py
`metadata-parser` has a bug in its current release. It also hasn't been worked on in more than two years. https://github.com/jvanasco/metadata_parser
In this PR, I re-implemented the webtool action library using beautifulsoup4. 
Current format
```
[ {'charset': 'utf-8'},
{'content': 'IE=edge', 'http-equiv': 'X-UA-Compatible'},
{'content': 'width=device-width, initial-scale=1', 'name': 'viewport'},
{'content': 'en', 'name': 'defaultLanguage'},
{ 'content': 'en, es, fr, ja, pt_BR, uk, el, de, zh_Hans, zh_Hant, ru, he, '
'eo',
'name': 'availableLanguages'},
{ 'content': 'A module to parse metadata out of urls and html documents',
'name': 'description'},
{ 'content': 'https://pypi.org/project/metadata-parser/',
'property': 'og:url'},
{'content': 'PyPI', 'property': 'og:site_name'}, …
```
> Replace metadataparser with a beautifulsoup4 solution

- jaseci_core/jaseci/extens/svc/elastic_svc.py
Currently, the generated elastic certificate only allow this hosts
{`service-name`}.{`namespace`}
- ex: `jaseci-es-internal-http.elastic`
{`service-name`}.{`namespace`}.svc
- ex: `jaseci-es-internal-http.elastic.svc`
all of this should work but not with `svc.cluster.local`
Tested in Kubernetes v1.25.4
> [ELASTIC-CERT]: Import elastic cert

- jaseci_ai_kit/jac_misc/setup.py
- jaseci_ai_kit/jac_nlp/jac_nlp/bart_sum/requirements.txt
- jaseci_ai_kit/jac_nlp/setup.py
- jaseci_ai_kit/jac_speech/setup.py
- jaseci_ai_kit/jac_vision/setup.py
- support/docker/jaseci.Dockerfile
* Fixes an issue where installing jac_nlp/jac_speech/jac_vision/jac_misc use cached pip wheel and could install older jaseci versions.
* We are now requiring a specific version of jaseci in setup.py for jac_*
* Also add `--no-cache-dir` to pip install when building docker image.
> Fix the case where an older version of jaseci is installed with jac_nlp/speech/vision

- jaseci_core/jaseci/extens/act_lib/date.py
- jaseci_core/jaseci/extens/act_lib/tests/fixtures/date.jac
- jaseci_core/jaseci/extens/act_lib/tests/test_date.py
- jaseci_core/jaseci/extens/svc/mail_svc.py
- jaseci_core/jaseci/extens/svc/tasks.py
```js
- EMAIL_BACKEND
- EMAIL_HOST
- EMAIL_PORT
- EMAIL_HOST_USER
- EMAIL_HOST_PASSWORD
- EMAIL_DEFAULT_FROM
- EMAIL_USE_TLS
- EMAIL_ACTIVATION_SUBJ
- EMAIL_ACTIVATION_BODY
- EMAIL_ACTIVATION_HTML_BODY
- EMAIL_RESETPASS_SUBJ
- EMAIL_RESETPASS_BODY
- EMAIL_RESETPASS_HTML_BODY
to
MAIL_CONFIG
{
**
"tls": true,
"host": "",
"port": 587,
"sender": "",
"user": "",
"pass": "",
"backend": "smtp",
"templates": {
"activation_subj": "Please activate your account!",
"activation_body": "Thank you for creating an account!\n\n"
"Activation Code: {{code}}\n"
"Please click below to activate:\n{{link}}",
"activation_html_body": "Thank you for creating an account!<br><br>"
"Activation Code: {{code}}<br>"
"Please click below to activate:<br>"
"{{link}}",
"resetpass_subj": "Password Reset for Jaseci Account", …
```
> [ENHANCEMENTS]: MInor changes and bugfixes: MailService, TaskService, DateAction

- jaseci_core/jaseci/extens/svc/elastic_svc.py
- jaseci_core/jaseci/jsorc/jsorc_settings.py
- jaseci_core/jaseci/jsorc/manifests/elastic.yaml
- jaseci_serv/jaseci_serv/base/example_jac/discussion_analysis.jac
- jaseci_serv/jaseci_serv/jac_api/tests/test_logging.py
- jaseci_serv/jaseci_serv/jac_api/views.py
This PR changes a number of configurations for the elastic stack to make it more scalable and suitable for production logging usage. Specifically,
* Configure a `data stream` for core and app logs.
* The data stream is configured with an elastic index lifecycle management (ILM) that
* Automatically rollover to create backing index for every 7 days or when the current index size reaches 1GB in size
* Automatically delete indices that are older than 14 days
* The data stream is also configured with a index template with useful mapping rules for ingesting logs
* `@timestamp` is mapped to `date` field in elastic so logs can be viewed/searched as timeseries data in Kibana
* text fields (except for `message`) are mapped to `keyword` field so they can be searched.
* Increase the storage size of …
> Better elastic configuration for production

- jaseci_ai_kit/jac_misc/jac_misc/openai/main.py
```python
api_key = os.environ.get("OPENAI_API_KEY")
api_base = os.environ.get("OPENAI_API_BASE", "https://api.openai.com/v1")
api_type = os.environ.get("OPENAI_API_TYPE", "open_ai")
api_version = (
"2023-03-15-preview" if api_type in ("azure", "azure_ad", "azuread") else None
)
```
> [OPENAI]: Support 3rd party AI provider

- jaseci_serv/jaseci_serv/base/models.py
- jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
- jaseci_serv/jaseci_serv/user_api/views.py
This PR adds a test that is supposed to reproduce a master unbecome bug where an admin user would seem to lose its admin privilege after becoming and un-becoming a normal user. However, I am not able to reproduce this in a test. I can still make it happen in jsctl. @marsninja we should take a look at this together.
> Master unbecome "bug" -- reproduce in test

- jaseci_core/jaseci/cli_tools/tests/ll.jac
- jaseci_core/jaseci/cli_tools/tests/ll_base.jac
- jaseci_core/jaseci/extens/act_lib/std.py
- jaseci_core/jaseci/jac/interpreter/interp.py
- jaseci_core/jaseci/jac/interpreter/walker_interp.py
- jaseci_core/jaseci/jac/machine/jac_value.py
- jaseci_core/jaseci/jac/machine/machine_state.py
- jaseci_core/jaseci/prim/ability.py
- jaseci_core/jaseci/prim/sentinel.py
- jaseci_core/jaseci/prim/walker.py
- jaseci_core/jaseci/tests/fixtures/ll.jac
- jaseci_core/jaseci/tests/jac_test_code.py
- jaseci_core/jaseci/tests/jac_test_progs.py
- jaseci_core/jaseci/tests/test_jac.py
- jaseci_core/jaseci/tests/test_progs.py
- jaseci_core/jaseci/utils/utils.py
- jaseci_serv/jaseci_serv/jac_api/tests/ll.jac
- jaseci_serv/jaseci_serv/jac_api/tests/test_jac_api.py
- jaseci_serv/jaseci_serv/jac_api/tests/zsb.jac
- Improved error pointer.
- Most of the exception should return the actual exception instead of the custom message.
- library from actions should return the actual exception instead of just returning error occured triggering call ability
- Code will now stop executing when error occures. This will be safer on process as it will immediately halt the process and avoid further breakage due to unexpected data created by the error. This is similar to current Try-Catch behavior. Even without using Try-Catch, developer should be able to get the exact error and position of the Exception including the stack trace for internal jaseci debugging.
- Try catch should include proper stack trace
---
```js
walker t1 {
a = {};
report a["a"];
}
walker t2 {
a = [];
report a[1];
}
walker t3 {
try {
a = {}; …
```
> [TRY-CATCH]: Improve message and code position

- jaseci_core/jaseci/extens/act_lib/tests/fixtures/webtool.jac
- jaseci_core/jaseci/extens/act_lib/webtool.py
MINOR:
- Use different url for get_meta_need_auth as previous URL ([google docs](https://docs.google.com/presentation/d/1lIYEuzzhZZ9PJaG_u3XgrFXX5Y6xd0zHV-aB2F8bXXU/edit)) doesn't have meta if loaded without javascript
> [BUGFIX]: Webtool optional headers

- jac/jaclang/compiler/passes/tool/jac_formatter_pass.py
- jac/jaclang/compiler/passes/tool/tests/fixtures/general_format_checks/line_spacing.jac
Formatter: fix comments placements after Ability Name
> Fix: Comment placement with LBrace

- jac/jaclang/compiler/absyntree.py
- jac/jaclang/compiler/passes/main/fuse_typeinfo_pass.py
- jac/jaclang/compiler/passes/main/import_pass.py
- jac/jaclang/compiler/passes/main/sym_tab_build_pass.py
- jac/jaclang/compiler/passes/main/tests/test_type_check_pass.py
- jac/jaclang/langserve/engine.py
- jac/jaclang/langserve/tests/test_server.py
- jac/jaclang/tests/fixtures/builtins_test.jac
- jac/jaclang/tests/test_cli.py
- jac/jaclang/utils/treeprinter.py
> Auto import builtin in jac files, support BuiltinType in fuse type info

- jac/jaclang/compiler/passes/main/fuse_typeinfo_pass.py
- jac/jaclang/compiler/passes/main/tests/fixtures/mod_type_assign.jac
- jac/jaclang/compiler/passes/main/tests/test_typeinfo_pass.py
This PR enhances the handling of `Assignment` nodes to correctly assign types and Symbol tables for variables when dealing with `ModuleType`. It now supports cases like `target = module` and ` target1 = target2 = module`.
In the example:
-  kl, l1, and l2 now have the correct type (Module) and are associated with the appropriate SymbolTable.
- target1, target2 = Val1, Val2 
- target = a.b.c                
- a.b.c = val
> Fix assignment for a target with a moduleType value

- jac/jaclang/compiler/parser.py
- jac/jaclang/tests/fixtures/match_multi_ex.jac
- jac/jaclang/tests/test_language.py
A bug in Jac's match statement fixed and enhanced its functionality by supporting multiple expressions within a single case.
Changes:
1. Bug fix in `parse.py`
2. Test file added (`match_multi_ex.jac`) in fixtures folder
3. New test function added (`test_match_multi_ex`) in `test_language.py` file
> Fix match Statement for Multiple Expressions in a single case

- jac/jaclang/runtimelib/importer.py
This PR fixes python parent directory imports that have submodules e.g `import:py from ..test_module.utils {x}` or `import:py from ...test_module.sub_module.utils {b}`
> Importer fix

- jac/jaclang/runtimelib/machine.py
- jac/jaclang/tests/fixtures/dynamic_architype.jac
- jac/jaclang/tests/test_language.py
This PR introduces the ability for JacMachine to dynamically instantiate nodes and walkers at runtime using `spawn_node` and `spawn_walker`. These features enhance flexibility by allowing users to create and manage architypes on-the-fly without reloading modules.
> Initial commit for creating Architype

- jac/jaclang/plugin/default.py
- jac/jaclang/tests/fixtures/visit_order.jac
- jac/jaclang/tests/test_language.py
This PR addresses the issue #1350 of inconsistent node traversal order during graph walks. It ensures nodes are visited in the order they are attached to the root node, as expected.
> Fix: Consistent Node Traversal Order in Walk

- jac-cloud/jac_cloud/plugin/jaseci.py
> Fix with entry/exit behavior on no node type in jac cloud

- jac/jaclang/plugin/default.py
- jac/jaclang/tests/fixtures/builtin_dotgen.jac
- jac/support/jac-lang.org/mkdocs.yml
1. Omitting Generic edge label updated in default.py file
2. Corresponding test case modified builtin_dotgen.jac
3. Changed old jac repo link to current Jaseci repo in mkdocs.yml file
> Ds edge enhancement

- jac/jaclang/cli/cli.py
- jac/jaclang/compiler/absyntree.py
- jac/jaclang/compiler/codeloc.py
- jac/jaclang/compiler/parser.py
- jac/jaclang/compiler/passes/ir_pass.py
- jac/jaclang/compiler/passes/main/import_pass.py
- jac/jaclang/compiler/passes/main/pyast_load_pass.py
- jac/jaclang/compiler/passes/transform.py
- jac/jaclang/runtimelib/machine.py
- jac/jaclang/tests/test_language.py
- jac/jaclang/utils/helpers.py
- jac/jaclang/utils/lang_tools.py
Description
Now the alerts are printed with the visual location indication for the end user to understand cleanly. Here are the screen shots of the implementation and the old one.
Current:
Previous:
> syntax error pretty print implemented

- jac/jaclang/compiler/symtable.py
- jac/jaclang/langserve/engine.py
- jac/jaclang/langserve/tests/test_server.py
- jac/jaclang/langserve/utils.py
This PR adds autocompletion support for built-in functions in Jaclang within the VS Code extension. When users begin typing, e.g., entering p, it now suggests built-in functions such as print,,.... and others. This improvement enhances coding efficiency by offering autocompletion options for commonly used functions.
> AutoCompletion suggestion for builtin functions : print, len, etc.

- jac-cloud/jac_cloud/core/architype.py
```python
node A {
has data: bytes;
}
```
- this is still needed to be converted to serializable object when trying to return to API
> [HOTFIX]: Fix saving bytes to db

- jac/jaclang/compiler/passes/main/def_impl_match_pass.py
- jac/jaclang/compiler/passes/main/tests/test_decl_def_match_pass.py
- jac/jaclang/compiler/passes/main/tests/test_def_use_pass.py
- jac/jaclang/tests/fixtures/decl_defn_param_name.jac
- jac/jaclang/tests/test_cli.py
```py
obj SomeClass {
can method1(some_long_paramenter_name: int) -> None;
can method2(param1:int, param2:str) -> None;
}
:o:SomeClass:c:method1(short_name:int) -> None {
print("short_name =", short_name);
}
:o:SomeClass:c:method2(p1:int, p2: str) -> None {
print("p1 =", p1, ", p2 =", p2);
}
with entry {
sc = SomeClass();
sc.method1(42);
sc.method2(64, "foobar");
}
```
> definition and declaration can have different parameter names

- jac/examples/micro/jac_cli.jac
- jac/jaclang/compiler/passes/main/def_impl_match_pass.py
- jac/jaclang/compiler/passes/main/tests/fixtures/uninitialized_hasvars.jac
- jac/jaclang/compiler/passes/main/tests/test_decl_def_match_pass.py
- jac/jaclang/compiler/passes/tool/tests/fixtures/corelib.jac
- jac/jaclang/compiler/passes/tool/tests/fixtures/corelib_fmt.jac
- jac/jaclang/compiler/tests/test_parser.py
```py
obj Test1 {
has var1: int;
has var2: int = 42;
has var3: int; # <-- This should be syntax error.
}
obj Test2 {
has var1: int;
has var2: int;
has var3: int;
has var4: int = 42;
can init() {  # <-- Should be error because "var2", "var3" are not initialized.
self.var1 = 1;
}
}
obj Test3 {
has var1: int;
has var2: int;
has var3: int;
has var4: int = 42;
can init();
}
:obj:Test3:can:init() {
self.var1 = 1;
}
```
> semantic errors for uninitialized obj hasvars

- jac/jaclang/compiler/passes/ir_pass.py
- jac/jaclang/compiler/passes/main/__init__.py
- jac/jaclang/compiler/passes/main/fuse_typeinfo_pass.py
- jac/jaclang/compiler/passes/main/import_pass.py
- jac/jaclang/compiler/passes/main/sym_tab_build_pass.py
- jac/jaclang/compiler/passes/main/tests/fixtures/pygame_mock/__init__.py
- jac/jaclang/compiler/passes/main/tests/fixtures/pygame_mock/__init__.pyi
- jac/jaclang/compiler/passes/main/tests/test_import_pass.py
- jac/jaclang/compiler/symtable.py
- jac/jaclang/langserve/tests/test_server.py
- jac/jaclang/tests/test_language.py
- jac/jaclang/utils/treeprinter.py
The goal of this implementation is to retrieve the needed symbols from the symbol table of imported modules and add them to the current module's symbol table (the module containing the import node itself).
The AST of the imported modules must be absorbed into the main program's AST.
1. **Added `**kwargs` to the `Pass` class**  
This allows sending switches to the `Pass`.
2. **Introduced a new flag `stop_inherit` in `SymTabBuildPass`**  
- Used the `**kwargs` handling to add the `stop_inherit` flag.  
- Prevents `SymTabBuildPass` from adding the new symbol table as a child of the parent table. Instead, it only creates the symbol table without attaching it to the SymbolTable tree.
3. **Created a list for `import from` nodes and their imported modules**  
- This list is processed after the …
> [PR2] Py decl symtable construct

- jac-cloud/jac_cloud/core/memory.py
- jac-cloud/jac_cloud/tests/openapi_specs.yaml
- jac-cloud/jac_cloud/tests/simple_graph.jac
- jac-cloud/jac_cloud/tests/test_simple_graph.py
First trigger of memory sync can possibly load additional architypes if needed
Second trigger will handle it
> [MEMORY]: Improve memory syncing

- jac-cloud/jac_cloud/core/architype.py
- jac-cloud/jac_cloud/core/memory.py
- jac-cloud/jac_cloud/plugin/jaseci.py
- jac-cloud/jac_cloud/tests/openapi_specs.yaml
- jac-cloud/jac_cloud/tests/simple_graph.jac
- jac-cloud/jac_cloud/tests/test_simple_graph.py
- jac/jaclang/plugin/default.py
- jac/jaclang/plugin/feature.py
- jac/jaclang/plugin/spec.py
- jac/jaclang/plugin/tests/fixtures/savable_object.jac
- jac/jaclang/plugin/tests/test_jaseci.py
- jac/jaclang/runtimelib/architype.py
Support ObjectAnchor/ObjectArchitype saving similar to Node/Edge/Walker
> [FEATURE]: Savable Object

- jac/jaclang/compiler/absyntree.py
- jac/jaclang/compiler/passes/main/inheritance_pass.py
- jac/jaclang/compiler/passes/main/schedules.py
- jac/jaclang/langserve/tests/test_server.py
- jac/jaclang/settings.py
- jac/jaclang/tests/fixtures/base_class1.jac
- jac/jaclang/tests/fixtures/base_class2.jac
- jac/jaclang/tests/fixtures/test_py.py
- jac/jaclang/tests/test_cli.py
> [Issue #1345 fix] Sub class symtab fix

- jac-cloud/jac_cloud/core/architype.py
- jac-cloud/jac_cloud/plugin/jaseci.py
- jac-cloud/jac_cloud/tests/openapi_specs.yaml
- jac-cloud/jac_cloud/tests/simple_graph.jac
- jac-cloud/jac_cloud/tests/test_simple_graph.py
- jac/jaclang/plugin/default.py
- jac/jaclang/runtimelib/architype.py
- jac/jaclang/runtimelib/utils.py
- jac/jaclang/tests/fixtures/visit_sequence.jac
- jac/jaclang/tests/test_language.py
- jac/support/jac-lang.org/docs/learn/data_spatial/sequence.md
- jac/support/jac-lang.org/mkdocs.yml
PREVIOUS BEHAVIOR:
`walker generic entry` **=>** `node entries (generic/typed)` **=>** _back to_ `walker typed entry` **=>** `walker typed exit` **=>** _back to_ `node exits (generic/typed)` => _back to_ `walker generic exit`
REFACTORED BEHAVIOR:
`walker generic entry` **=>** `walker typed entry` **=>** `node generic entry` **=>** `node typed entry` **=>** `node typed exit` **=>** `node generic exit` **=>** _back to_ `walker typed exit` **=>** `walker generic exit`
In this approach, we limit the back and forth of execution to `walker -> node -> walker`. It can also make the execution more "declarative".
It's also more direct if we plan in future to support the `with entry` and `with exit` approach
> [REFACTOR]: Spawn Call

- jac-cloud/jac_cloud/jaseci/__init__.py
- jac-cloud/jac_cloud/jaseci/datasources/redis.py
- jac-cloud/jac_cloud/jaseci/dtos/__init__.py
- jac-cloud/jac_cloud/jaseci/dtos/webhook.py
- jac-cloud/jac_cloud/jaseci/models/__init__.py
- jac-cloud/jac_cloud/jaseci/models/webhook.py
- jac-cloud/jac_cloud/jaseci/routers/__init__.py
- jac-cloud/jac_cloud/jaseci/routers/webhook.py
- jac-cloud/jac_cloud/jaseci/security/__init__.py
- jac-cloud/jac_cloud/plugin/jaseci.py
- jac-cloud/jac_cloud/tests/openapi_specs.yaml
- jac-cloud/jac_cloud/tests/simple.json
- jac-cloud/jac_cloud/tests/simple_graph.jac
- jac-cloud/jac_cloud/tests/test_simple_graph.py
- jac-cloud/jac_cloud/tests/test_utils.py
- jac/support/jac-lang.org/docs/learn/coders/jac-cloud/docs/jac_cloud_webhook.md
- jac/support/jac-lang.org/mkdocs.yml
- webhook walker is similar to normal authenticated walker however, normal authenticated walker is associated to a user while webhook is directly to root.
- webhook api keys are manage by user
- supports different HTTP components as API key holder
- header (default):
- query
- path
- body
- name of the api-key can be change to any string (default: `X-API-KEY`)
```python
walker webhook {
can enter1 with `root entry {
report here;
}
class __specs__ {
has webhook: dict = {
"type": "header | query | path | body", # optional: defaults to header
"name": "any string" # optional: defaults to X-API-KEY
};
}
}
```
> **POST** /webhook/generate-key
```python
{
"name": "webhook1",
"walkers": ["webhook"], 
"nodes": ["root"],
"expiration": {
"count": 60,
"interval": "days"
}
}
```
```python
{
"id": …
```
> [WEBHOOK]: Initial integration

- jac/jaclang/compiler/absyntree.py
- jac/jaclang/compiler/passes/main/import_pass.py
- jac/jaclang/compiler/tests/test_importer.py
- jac/jaclang/runtimelib/importer.py
- jac/jaclang/runtimelib/machine.py
This PR refines the `run_import` method to improve the module import process for Jac files. Key improvements include:
Enhanced Search Path Resolution:
* The method effectively incorporates **JACPATH** and the caller directory to locate modules.
* Handles both directory modules and .jac files with improved checks.
> Enhance Module Import Logic

- jac/jaclang/utils/helpers.py
fixed warning in jac tool gen_parser . i change the 'jac_ref.md' file path as '../support/jac-lang.org/docs/lang_ref/jac_ref.md' .
> fix warning jac tool gen_parser

- jac/jaclang/compiler/parser.py
- jac/jaclang/compiler/tests/test_parser.py
```py
self.consume(a) -> return the node
self.match(b)     -> return the node or none
self.match_many(c) -> 0 or more
self.consume_many(d) -> 1 or more
```
```py
#rule: name (COMMA name)*  // <-- This is parsed as:
names: listp[ast.Name] = []
names.append(self.consume(ast.Name))
while self.match_token(Tok.COMMA):
names.append(self.consume(ast.Name))
```
```py
self.consume_token(Tok.FROM) # from
self.consume_token(Tok.DOT)  # ...
level = 0
while True:
if self.match_token(Tok.DOT):
level += 1
elif self.match_token(Tok.ELIPSE):
level += 3
attrib = self.match(ast.Attribute) # foo.bar.baz
self.consume_token(Tok.IMPORT) # import
items = []
while name := self.match(ast.Name): # foo as f, bar as b
name.alias = self.match(ast.Alias)
items.append(name)
self.match_token(Tok.COMMA) …
```
> [Parser] match, consume methods added

- jac/jaclang/compiler/jac.lark
- jac/jaclang/utils/helpers.py
- jac/support/jac-lang.org/docs/lang_ref/jac_ref.md
* Lark reference heading line should starts with `// [Heading]:`. Now we can write our own comments without messing with the reference generator.
* Terminals / Tokens are the lego blocks of a language (ast) so I've grouped them together in a meaningful way.
> [Lark-PR-1] lark tokens are grouped

- jac-cloud/README.md
- jac-cloud/jac_cloud/tests/openapi_specs.yaml
> jac-cloud changed in readme

- jac/jaclang/compiler/absyntree.py
- jac/jaclang/compiler/parser.py
- jac/jaclang/compiler/passes/main/pyast_gen_pass.py
- jac/jaclang/compiler/passes/main/pyast_load_pass.py
- jac/jaclang/compiler/passes/main/pyout_pass.py
- jac/jaclang/compiler/passes/tool/jac_formatter_pass.py
- jac/jaclang/compiler/passes/tool/tests/fixtures/genai/joke_gen.jac
- jac/jaclang/compiler/passes/tool/tests/fixtures/genai/odd_word_out.jac
- jac/jaclang/compiler/passes/tool/tests/fixtures/genai/wikipedia.jac
- jac/jaclang/compiler/symtable.py
> subnode list removed from list

- jac/jaclang/compiler/constant.py
- jac/jaclang/compiler/jac.lark
- jac/jaclang/compiler/parser.py
- jac/support/jac-lang.org/docs/lang_ref/jac_ref.md
* Both STRING and DOC_STRING are now strings in terms of literal values
* `module` rule in lark is simplified.
> [Lark-PR-2] Module rule simplified

- jac/jaclang/compiler/passes/main/inheritance_pass.py
- jac/jaclang/tests/fixtures/base_class_complex_expr.jac
- jac/jaclang/tests/test_cli.py
Fixing a crash due to two unsupported forms of base class. The fix is just reporting that this is not supported. The issue here is that the inheritance pass depends on fuse type info to get the types of the complex base class expressions, fuse type info depends on inheritance class too for atom trailers. so we need some iterative process to run both of them multiple times.
> Fixing a crash due to complex base class expressions not supported

- jac-cloud/jac_cloud/jaseci/routers/healthz.py
- jac-cloud/jac_cloud/jaseci/routers/sso.py
- jac-cloud/jac_cloud/jaseci/routers/user.py
- jac-cloud/jac_cloud/jaseci/routers/webhook.py
- jac-cloud/jac_cloud/plugin/__init__.py
- jac-cloud/jac_cloud/plugin/implementation/__init__.py
- jac-cloud/jac_cloud/plugin/implementation/api.py
- jac-cloud/jac_cloud/tests/openapi_specs.yaml
- jac-cloud/jac_cloud/tests/simple_graph.jac
- jac/support/jac-lang.org/docs/for_coders/jac-cloud/jac_cloud.md
```python
walker ask_question {
class __specs__ {
has allow_entry: bool = False, tags: list[str] = ["Chat APIs"];
}
}
```
- customization of tags to segregate OpenAPI specifications/docs
- "NODE" for generating api with `/{node}` entry input. "ROOT" for generating api without node entry input (always current root entry). "BOTH" will support both.
```python
walker documentation {
class __specs__ {
has tags: list[str] | None = ["Documented"];
has entry_type: EntryType = "root";
has status_code: int | None = "201";
has summary: str | None = "Enter summary here!!!";
has description: str | None = "Enter description here!!!";
has response_description: str = "Enter response description here!!! Defaults to 'Successful Response'";
has responses: dict[int | str, dict[str, Any]] | None = {
200: { …
```
> [MINOR]: Additional API Configuration for documentations

- jac-cloud/jac_cloud/jaseci/routers/webhook.py
- jac-cloud/jac_cloud/plugin/implementation/websocket.py
> [WEBSOCKET]: Align websocket encoder to rest encoder

- jac/jaclang/__init__.py
- jac/jaclang/compiler/passes/main/pyast_gen_pass.py
- jac/jaclang/runtimelib/context.py
In jaclib `root` changed into `root()`
FIX: https://github.com/Jaseci-Labs/jaseci/issues/1600
> Global root removed and root() returns the ctx root.

- jac/jaclang/compiler/passes/main/pyast_gen_pass.py
- jac/jaclang/tests/fixtures/refs_target.jac
- jac/jaclang/tests/test_language.py
A but in the codegen of `Node.refs()` fixed, The argument `target` was always `None`.
```
node a { has val:int=0; }
node b { has val:int=0; }
node c { has val:int=0; }
with entry {
x = [a(val=i) for i in range(0,3)];
y = [b(val=i) for i in range(0,3)];
z = [c(val=i) for i in range(0,3)];
x ++> y;
y ++> z;
print([x-->y-->z]);
print([x-->y[:1]-->z[:1]]);
}
```
> A bug in targ argument of jaclib Node.refs() fixed

- jac/jaclang/compiler/passes/main/import_pass.py
- jac/jaclang/compiler/passes/main/sym_tab_link_pass.py
- jac/jaclang/compiler/passes/main/tests/fixtures/symtab_link_tests/action/__init__.py
- jac/jaclang/compiler/passes/main/tests/fixtures/symtab_link_tests/action/actions.jac
- jac/jaclang/compiler/passes/main/tests/fixtures/symtab_link_tests/main.jac
- jac/jaclang/compiler/passes/main/tests/test_sym_tab_link_pass.py
Fix for : https://github.com/Jaseci-Labs/jaseci/issues/1750
This PR addresses a bug in the SymTabLinkPass where `__init__.jac` and `__init__.py` files were not handled correctly,
and this is now resolved.
Error Trace
```
File "/Users/chrisisking/dev/trueselph/jivas/venv/lib/python3.12/site-packages/jaclang/compiler/passes/main/sym_tab_link_pass.py", line 36, in enter_module_path
imported_mod_symtab = self.prog.modules[rel_path].sym_tab
~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: './jivas/agent/core/__init__.jac'
```
> [Jivas Fix] Handle __init__ Files in Package Imports 

- jac/support/vscode_ext/jac/package.json
- jac/support/vscode_ext/jac/src/extension.ts
- jac/support/vscode_ext/jac/src/utils.ts
This PR adds support for discovering and selecting the jac executable environment in the VS Code extension. Users can now switch between environments via a new status bar item.
Clone and build the extension:
```
git clone https://github.com/Jaseci-Labs/jaseci.git
cd ~/jaseci/jac/support/vscode_ext/jac
npm install
npm install -g @vscode/vsce
vsce package
code --install-extension <path-to-generated-vsix>
```
Replace <path-to-generated-vsix> with the actual filename (e.g., jaclang-extension-2024.x.x.vsix).
Press Ctrl+Shift+P → Select Reload Window.
This is located at the bottom of the VS Code window.
https://github.com/user-attachments/assets/a6a6c96e-db18-4748-96c6-62f715656e68
🎉 Happy Coding!
> Add: Environment discovery and selection for Jac executable in VSCE

- jac/jaclang/compiler/passes/main/pyast_load_pass.py
- jac/jaclang/tests/fixtures/py_namedexpr.py
- jac/jaclang/tests/test_language.py
- build NamedExpr as AtomUnit for walrus operator
- add regression test for NamedExpr
- `pre-commit run --files jac/jaclang/compiler/passes/main/pyast_load_pass.py jac/jaclang/tests/fixtures/py_namedexpr.py jac/jaclang/tests/test_language.py` *(fails: command not found)*
> Fix walrus conversion

- jac/examples/reference/concurrent_expressions.py
- jac/examples/reference/special_comprehensions.py
- jac/jaclang/compiler/passes/main/pyast_gen_pass.py
- jac/jaclang/runtimelib/machine.py
- infer module language when importing
- stop passing `lng` arg when importing
- update examples using `py_jac_import`
- `python -V`
> Auto infer jac_import language

- jac-splice-orc/jac_splice_orc/plugin/splice_plugin.py
- jac/jaclang/compiler/unitree.py
- jac/jaclang/runtimelib/machine.py
- jac/jaclang/utils/__init__.py
- jac/jaclang/utils/module_resolver.py
- provide new module_resolver with functions to locate module paths and infer language
- use infer_language from module_resolver in machine and splice plugin
- update unitree to delegate path resolution to new utility
- expose utilities via jaclang.utils
- remove old infer_language implementation
- `python -m py_compile jac/jaclang/utils/module_resolver.py jac/jaclang/runtimelib/machine.py jac/jaclang/compiler/unitree.py jac-splice-orc/jac_splice_orc/plugin/splice_plugin.py`
- `pip install pytest` *(fails: Could not find a version that satisfies the requirement pytest)*
> Centralize path inference utilities

- docs/docs/extra.css
- docs/docs/js/pyodide-worker.js
- docs/docs/js/run-code.js
- docs/docs/learn/language_basics/basic_syntax.md
- docs/mkdocs.yml
* Added a Pyodide-based web worker in `docs/docs/js/pyodide-worker.js` to load the Pyodide environment, install the `jaclang` package, and execute Jac code. The worker handles messages for initialization and code execution, returning the output or errors to the main thread.
* Implemented `run-code.js` to manage the interaction with the Pyodide worker, including initializing the worker, running Jac code, and defining a custom `code-block` HTML element for interactive code snippets.
* Updated `docs/docs/extra.css` to include styles for the new `.code-container` class, which provides a styled container for code snippets, buttons, and output blocks. The styles include hover and active states for buttons and transitions for the output area.
* Updated `docs/mkdocs.yml` to include the Pyodide …
> Create a Custom div to execute the jac code in MKDOCS

- docs/docs/learn/jac_in_a_flash.md
- elaborate on each tutorial step in `jac_in_a_flash.md`
- describe syntax features such as `obj`, `has`, `|>`, `impl`, and walker traversal
- `pre-commit run --files docs/docs/learn/jac_in_a_flash.md` *(fails: command not found)*
> Expand Jac in a Flash tutorial

- jac/support/vscode_ext/jac/src/commands/index.ts
The `getJacPath` command was unintentionally removed in the last PR, which will break visual debugger. This PR restores it.
--------------------
--------
After Fix
----------
https://github.com/user-attachments/assets/e2516fd1-9217-4b68-8d91-cd61125d606c
> [ QuickFix- VSCE ] : getJacPath-fix

- docs/docs/learn/introduction.md
- populate introduction sections with content from across the docs
- add small Jac code snippets showing each concept
- `pre-commit` *(fails: command not found)*
- `pytest` *(fails: command not found)*
- `mkdocs build` *(fails: command not found)*
> Populate introduction sections

- docs/docs/internals/planning_specs/native_type_system/lets_build.md
- fix comments inside mermaid diagrams so they render properly
- `pytest -q jac-mtllm/tests/test_jaclang.py -k test_with_llm_function` *(fails: ImportError: cannot import name 'jac_import')*
> Fix mermaid diagrams in lets_build

- docs/docs/404.md
- docs/scripts/mkdocs_serve.py
* `docs/scripts/mkdocs_serve.py`: Updated the `send_error` method to serve the 404 page (`404.html`) when a 404 error occurs.
> Add 404 error handling in MkDocs Doc

- jac/examples/reference/check_statements.md
- jac/examples/reference/context_managers.md
- jac/examples/reference/control_statements.md
- jac/examples/reference/data_spatial_spawn_expressions.md
- jac/examples/reference/data_spatial_typed_context_blocks.md
- jac/examples/reference/disengage_statements.md
- jac/examples/reference/free_code.md
- jac/examples/reference/function_calls.md
- jac/examples/reference/lambda_expressions.md
- jac/examples/reference/match_statements.md
- jac/examples/reference/raise_statements.md
- jac/examples/reference/return_statements.md
- jac/examples/reference/tests.md
- jac/examples/reference/try_statements.md
- jac/examples/reference/while_statements.md
- jac/examples/reference/yield_statements.md
- correct comment syntax in reference Markdown files
- `pre-commit run --files jac/examples/reference/check_statements.md jac/examples/reference/context_managers.md jac/examples/reference/control_statements.md jac/examples/reference/data_spatial_spawn_expressions.md jac/examples/reference/data_spatial_typed_context_blocks.md jac/examples/reference/disengage_statements.md jac/examples/reference/free_code.md jac/examples/reference/function_calls.md jac/examples/reference/lambda_expressions.md jac/examples/reference/match_statements.md jac/examples/reference/raise_statements.md jac/examples/reference/return_statements.md jac/examples/reference/tests.md jac/examples/reference/try_statements.md jac/examples/reference/while_statements.md jac/examples/reference/yield_statements.md` *(fails: …
> Fix comment syntax in Jac reference docs

- docs/docs/learn/jac_coding_manual.md
- adjust heading levels in `jac_coding_manual.md`
- ensure Part headings use `#` and chapter headings use `##`
- `pre-commit run --files docs/docs/learn/jac_coding_manual.md` *(fails: couldn't connect to pre-commit hooks)*
- `pytest -q` *(fails: ModuleNotFoundError: No module named 'dotenv')*
> Fix header hierarchy in Jac coding manual

- docs/mkdocs.yml
- docs/pyproject.toml
- docs/scripts/mkdocs_serve.py
* Replaced the custom HTTP server (`http.server` + `socketserver`) with a Starlette + Uvicorn-based implementation for serving the MkDocs site. This includes adding middleware for security headers (`SecurityHeadersMiddleware`) and mounting static files using Starlette's `StaticFiles`.
* Removed the `CustomHeaderHandler` class and replaced it with the `SecurityHeadersMiddleware`, which adds COOP and COEP headers to responses.
* Updated the `mkdocs.yml` configuration to explicitly disable `navigation.instant` by setting it to `false`. This ensures predictable navigation behavior.
> Change the doc running server to uvicorn

- docs/docs/communityhub/release_notes.md
- jac/jaclang/compiler/unitree.py
- jac/jaclang/tests/fixtures/unicode_strings.jac
- jac/jaclang/tests/test_language.py
Issue
- Unicode characters in Jac string literals were being corrupted during compilation
- Characters like "✓" and "○" were converted to byte sequences like `'â\x9c\x93'` and `'â\x97\x8b'`
Fix
- Removed `encode().decode("unicode_escape")` approach that was corrupting unicode characters
- Now uses Python's built-in `ast.literal_eval()` for safe and proper string literal evaluation
> [BugFix] Support unicode

- docs/docs/extra.css
- docs/mkdocs.yml
- docs/overrides/partials/footer.html
* `docs/docs/extra.css` Added a `.md-ellipsis` class for padding, adjusted tab navigation styling with additional padding, and introduced styles for a custom footer, including `.footer`, `.footer-content`, and `.footer-links` classes for layout, colors, and hover effects.
* `docs/docs/extra.css`: Reformatted CSS variable comments for better readability in the `--md-primary-fg-color`, `--md-primary-bg-color`, and related variables.
* `docs/mkdocs.yml`: Configured a custom theme directory (`custom_dir: overrides`) to support theme overrides.
* `docs/overrides/partials/footer.html`: Added a custom footer with links to GitHub, the community, and documentation, along with copyright and a tagline.
> Adjust the Styling in Doc

- jac/jaclang/compiler/passes/main/cfg_build_pass.py
- jac/jaclang/compiler/passes/main/tests/test_cfg_build_pass.py
The CFG links were not created correctly since the removal of subnode list ast nodes which the underlying algorithm depended upon. Instead a new algorithm to get a sequence of operations are integrated, that made the existing tests pass.
> [UniiR] The CFG links are fixed and the tests are reinstated 

- docs/scripts/handle_jac_compile_data.py
- docs/scripts/mkdocs_serve.py
This approach ensures that the zip file always contains the latest version of the jaclang folder and its contents. It prevents issues where stale or outdated files might remain in the zip archive if files are deleted or updated in the source directory. By recreating the zip file on every rebuild, we guarantee that the playground always serves the most up-to-date and consistent version of the codebase.
> Refactor: update pre-build hook to remove existing jac-lang zip file and recreate

- docs/docs/playground/jac_examples.json
- docs/scripts/handle_jac_compile_data.py
* Updated example references to use a more intuitive folder structure by replacing "reference" with "basic" and renaming "Data Spatial Programming" to "Object Spatial Programming."
* Removed the `copy_example_folder` function, which handled copying `.jac` files to documentation assets. This function is no longer needed, simplifying the script.
* Updated the `pre_build_hook` function to remove the call to `copy_example_folder`, aligning with the removal of the function itself.
> Update example paths and remove copy examples function

- docs/docs/index.html
- docs/scripts/handle_jac_compile_data.py
- scripts/top_contributors.py
* Updated `get_top_contributors` in `handle_jac_compile_data.py` to accept a list of repositories, enabling the generation of contributor data for multiple repositories. [[1]](diffhunk://#diff-a685ea3ac80af296a291c1a1a266444af05166a7da9b5b409eaaca6d9805c861L51-R60) [[2]](diffhunk://#diff-a685ea3ac80af296a291c1a1a266444af05166a7da9b5b409eaaca6d9805c861L90-R108)
* Modified the `main` function in `scripts/top_contributors.py` to handle a primary repository and additional repositories via a new `--extra-repos` argument.
* Added functions (`get_tabs_html`, `get_tab_contents_html`, `print_tabbed_tables`) in `scripts/top_contributors.py` to generate a tabbed HTML view for displaying contributor data across multiple repositories.
* Introduced CSS (`get_tabs_css`) and JavaScript (`get_tabs_js`) …
> Extend leaderboard to jivas and playground

- docs/docs/communityhub/release_notes.md
- docs/docs/learn/jac-cloud/permission.md
- jac-cloud/jac_cloud/plugin/jaseci.py
- jac-cloud/jac_cloud/tests/openapi_specs.yaml
- jac-cloud/jac_cloud/tests/simple_graph.jac
- jac-cloud/jac_cloud/tests/test_simple_graph.py
- jac/jaclang/runtimelib/archetype.py
- jac/jaclang/runtimelib/machine.py
- jac/jaclang/runtimelib/tests/fixtures/custom_access_validation.jac
- jac/jaclang/runtimelib/tests/test_jaseci.py
This is to support complex access validation. Since we can now do anything, dev should be able to implement/integrate access handler from other frameworks/library or at least replicate it.
!!! The only limitation right now is, we only validates it from current root. We don't implement "from" node yet. This means on `__jac_access__` you don't have direct reference of the node you are from. Please let me know if we still need to support that
- access can now depends on attributes
Ex:
```
node bot {
has allowed_admins: list[str] = [];
def __jac_access__ {
current_root = Jac.get_root();
if jid(current_root) in self.allowed_admins {
return "WRITE"
}
return "NO_ACCESS"
}
}
```
- We can also query directly to DB
Ex:
```
node bot {
has allowed_admins: list[str] = [];
def __jac_access__ {
profile …
```
> [FEATURE]: Custom Access Validation

- jac/jaclang/compiler/passes/main/pyast_gen_pass.py
- jac/jaclang/compiler/passes/main/sem_def_match_pass.py
- jac/jaclang/compiler/passes/main/tests/fixtures/codegen_sem.jac
- jac/jaclang/compiler/passes/main/tests/test_pyast_gen_pass.py
- jac/jaclang/compiler/unitree.py
- jac/jaclang/runtimelib/machine.py
```py
def get_weather(city: str) -> str by llm();
sem get_weather = "Returns the weather for a given city.";
sem get_weather.city = "Name of the city to get the weather for.";
```
```py
@_.sem(
"Returns the weather for a given city.", {
"city" : "Name of the city to get the weather for.",
}
)
def get_weather(city: str):
...
```
closes: https://github.com/jaseci-labs/jaseci/issues/2211
> 🎯 Semstring are codegenerated to python (this is required to remove SemRegistry)

- jac/jaclang/compiler/passes/main/tests/test_pyast_gen_pass.py
> 🧪 Test added for semstrings in symbol table

- jac-cloud/jac_cloud/jaseci/datasources/localdb.py
- jac-cloud/jac_cloud/tests/test_simple_graph.py
ISSUE:
- SQLite only allow same thread instance usage. If it's on different thread, you need to initialize a new connection/client.
- FastAPI uses AnyIO for async handler. AnyIO propagate ContextVars on child Threads. When main thread's monty client (SQLite) is created, it propagates to all newly created threads.
> [BUGFIX]: Local DB uses same monty client across threads

- jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
- jac/jaclang/compiler/passes/tool/tests/fixtures/simple_walk_fmt.jac
> 🐛 Fix: `by llm` formatter

- jac/jaclang/cli/cli.py
- jac/jaclang/compiler/passes/main/pyast_load_pass.py
- jac/jaclang/runtimelib/importer.py
- jac/jaclang/tests/fixtures/pyfunc_fstr.py
- jac/jaclang/tests/test_cli.py
- jac/jaclang/utils/module_resolver.py
- This PR refactors the PyImporter to support running Python files using the jac run py_filepath command.
---------------
- Alongside the core refactor, this also fixes a key issue in parsing Python f-strings by properly mapping FString → MultiString.
-------
1. 
---------
2. 
------------
> Refactor PyImporter to load Python modules as Jac AST

- jac/jaclang/cli/cli.py
- jac/jaclang/compiler/unitree.py
- jac/jaclang/tests/fixtures/pyfunc_fmt.py
- jac/jaclang/tests/test_cli.py
----
- running Python files via `jac run`
- py2jac conversion
----------------
-------------
----------
> Temporary Patch: Avoid Format Failures during py2jac Conversion

- scripts/top_contributors.py
* [`scripts/top_contributors.py`](diffhunk://#diff-8f3c1b955ade1203f0bdcacff3b0f50630e4f79ad76de9a6931299670918ebf3L345-R346): Commented out the `DEFAULT_EXTRA_REPOS` list and replaced it with an empty list.
* [`scripts/top_contributors.py`](diffhunk://#diff-8f3c1b955ade1203f0bdcacff3b0f50630e4f79ad76de9a6931299670918ebf3L415-R416): Updated the `repos` list in the `main` function to exclude `args.extra_repos` by commenting out its inclusion.
> Temporary disable Jivas and jac playground from the leaderboard

- jac/jaclang/compiler/passes/main/tests/test_checker_pass.py
- jac/jaclang/compiler/type_system/type_evaluator.py
---------------------------
Since we are in the start of our typechecking journey, strict evaluation of unknown types is temporarily relaxed.
Assignments with unknown types will be treated as valid to avoid unnecessary failures until stricter rules are introduced later.
--------------------------
> ⌨️  Unknown type assignment are allowed

- docs/docs/js/pyodide-worker.js
- docs/docs/js/run-code.js
- docs/docs/learn/jac_in_a_flash.md
This task is about enabling interactive input() support when running Jac code inside the Pyodide worker. Currently, code execution works, but when input() is called, the Python side blocks and cannot receive the user’s response from the main thread. The goal is to implement a communication mechanism (via postMessage, SharedArrayBuffer, and Atomics) that lets the worker pause for input requests, prompt the user in the browser, and then resume execution with the provided string. This will make the Jac playground interactive for programs requiring user input.
> Code block enabling input handling | Getting Inputs from the User

- docs/docs/jac_book/chapter_5.md
- docs/docs/jac_book/chapter_9.md
- docs/docs/learn/examples/littleX/src/byllm_example.jac
- jac-byllm/examples/essay_review.jac
- jac-byllm/examples/joke_gen.jac
- jac-byllm/examples/text_to_type.jac
- jac/jaclang/compiler/passes/tool/tests/fixtures/simple_walk_fmt.jac
incl_info should be used pass in timly information such as datetime, as an expression evaluated at call time.
> Remove `incl_info` usages in repo and docs 

- docs/docs/communityhub/release_notes.md
- jac-byllm/pyproject.toml
- jac-cloud/pyproject.toml
- jac/pyproject.toml
The byLLM transitioning changed jaclang when recognizing the byllm plugin which is not pushed before byllm 0.4.1.
This PR bumps the version of all three to make sure everything remain compatible.
> New PyPI version upgrade to allow byLLM

- docs/docs/communityhub/release_notes.md
- Corrects a mistake in the previous release notes update where TypeChecker Diagnostics features and LSP improvements were incorrectly placed in version 0.8.6 instead of 0.8.7.
> 🔧 Fix Release Notes: Move TypeChecker Diagnostics from 0.8.6 to 0.8.7

- jac/jaclang/compiler/passes/main/tests/fixtures/checker_float.jac
- jac/jaclang/compiler/passes/main/tests/test_checker_pass.py
- jac/jaclang/compiler/type_system/type_evaluator.py
```
with entry {
pi = 3.14;     # <-- infer the type
f: float = pi; # <-- OK
s: str = pi;   # <-- Error
}
```
> 🛟 Float type check

- jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
- jac/jaclang/compiler/passes/tool/tests/fixtures/tagbreak.jac
Fix an issue with the extra line in the inner compr that is part of list/set/dict compr 
```
self.program.errors_had = [
e for e in self.program.errors_haddddddddd if e.loc.mod_path != file_path_fs
];
```
> Fix the issue of extra line in list/dict/set compr

- jac/jaclang/compiler/passes/tool/doc_ir_gen_pass.py
- jac/jaclang/compiler/passes/tool/tests/fixtures/tagbreak.jac
Fix for extra space printed after expr_as_item nodes 
```
with entry {
with open(f"Apple{apple}.txt") as f {
print(
f.read()
);
}
}
```
> Fixing the extra space printed after expr_as_item

- jac/support/vscode_ext/jac/syntaxes/jac.tmLanguage.json
I'm adding support to highlighting this language in [babi](https://github.com/asottile/babi) (my text editor).  babi uses vs code grammars which roughly use textmate syntax in json form.  this is one of the hints in the grammar file to tell the editor which file extensions are supported by a grammar (I assume the vs code extension does this through other means and doesn't need `fileTypes`)
> add fileTypes to textmate syntax
